import { useCallback, useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Empty, Icon, Note } from './ui';
import { canAccess, moduleById, parseRoute, roleById, roles, routeHash, sectionsFor, type ModuleId, type RoleId, type Route } from './navigation';
import { getVersion, prepareMasterShift, subscribe, tasks, type Scope } from './domain';
import { WorkspaceView, type Navigate } from './views';
import { Modal, ProductDrawer, SearchDialog } from './dialogs';
import { startPlantSync } from './plant-sync';
import { loadSecuritySession, selectDemoRole, type SecuritySession } from './security-client';

export default function App() {
  useSyncExternalStore(subscribe, getVersion);
  const [route, setRoute] = useState<Route>(() => parseRoute(window.location.hash));
  const [scope, setScope] = useState<Scope>('all');
  const [overlay, setOverlay] = useState<'search' | 'notifications' | null>(null);
  const [roleMenu, setRoleMenu] = useState(false);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [isNavCollapsed, setIsNavCollapsed] = useState(() => {
    try { return window.localStorage.getItem('orbita.nav.collapsed') === 'true'; } catch { return false; }
  });
  const [toast, setToast] = useState('');
  const [session, setSession] = useState<SecuritySession | null>(null);
  const [securityReady, setSecurityReady] = useState(false);
  const [securityError, setSecurityError] = useState('');
  const role = roleById[route.role]; const workspace = moduleById[route.module]; const sections = sectionsFor(route.role, route.module);
  const roleMenuRef = useRef<HTMLDivElement>(null);
  const passportReturn = useRef<Route | null>(null);
  useEffect(() => { void loadSecuritySession().then(value => value?.user.role === route.role ? value : selectDemoRole(route.role)).then(value => { prepareMasterShift(); setSession(value); setSecurityReady(true); }).catch(error => { setSecurityError(error instanceof Error ? error.message : 'Локальный сервер недоступен'); setSecurityReady(true); }); }, []);
  useEffect(() => { const listener = () => { const next = parseRoute(window.location.hash); setRoute(session && next.role !== session.user.role ? { role: session.user.role, module: 'home', section: '' } : next); setMobileMenu(false); }; window.addEventListener('hashchange', listener); return () => window.removeEventListener('hashchange', listener); }, [session]);
  useEffect(() => session ? startPlantSync() : undefined, [session]);
  useEffect(() => { if (session && route.role !== session.user.role) { const next = { role: session.user.role, module: 'home' as const, section: '' }; setRoute(next); window.location.hash = routeHash(next); } }, [session, route.role]);
  useEffect(() => { document.title = `${route.module === 'home' ? role.title : workspace.label} · ОРБИТА.QC`; }, [role.title, route.module, workspace.label]);
  useEffect(() => { try { window.localStorage.setItem('orbita.nav.collapsed', String(isNavCollapsed)); } catch { /* storage can be unavailable in private mode */ } }, [isNavCollapsed]);
  useEffect(() => { window.scrollTo({ top: 0 }); }, [route.role, route.module, route.section]);
  useEffect(() => { const listener = (e: KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); setOverlay(current => current === 'search' ? null : 'search'); } if (e.key === 'Escape') { setRoleMenu(false); setMobileMenu(false); } }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); }, []);
  useEffect(() => { const close = (event: PointerEvent) => { if (roleMenuRef.current && !roleMenuRef.current.contains(event.target as Node)) setRoleMenu(false); }; document.addEventListener('pointerdown', close); return () => document.removeEventListener('pointerdown', close); }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4000); return () => clearTimeout(timer); }, [toast]);
  const go = useCallback((next: Route) => { const secured = session ? { ...next, role: session.user.role } : next; const normalized = parseRoute(routeHash(secured)); setRoute(normalized); window.location.hash = routeHash(normalized); setMobileMenu(false); setRoleMenu(false); }, [session]);
  const navigate: Navigate = (module, section, item) => { if (canAccess(route.role, module)) go({ role: route.role, module, section: section ?? sectionsFor(route.role, module)[0]?.id ?? '', item }); };
  const openItem = (item: string) => { passportReturn.current = route.role === 'technologist' && route.module === 'investigation' ? route : null; go({ ...route, item, caseId: undefined }); };
  const openCase = (item: string, caseId: string) => go(route.role === 'controller' ? { role: 'controller', module: 'quality', section: 'signals', item, caseId } : route.role === 'technologist' ? { role: 'technologist', module: 'investigation', section: 'cases', item, caseId } : { ...route, item, caseId });
  const changeRole = (nextRole: RoleId, module: ModuleId = nextRole === 'controller' ? 'quality' : 'home') => {
    if (nextRole !== session?.user.role) {
      void selectDemoRole(nextRole).then(value => { setSession(value); const next = { role: nextRole, module, section: sectionsFor(nextRole, module)[0]?.id ?? '' }; setRoute(next); window.location.hash = routeHash(next); setRoleMenu(false); }).catch(error => setToast(error instanceof Error ? error.message : 'Не удалось переключить роль'));
      return;
    }
    go({ role: nextRole, module, section: sectionsFor(nextRole, module)[0]?.id ?? '' });
  };
  const scopedView = ['home', 'quality', 'products', 'production', 'operations', 'investigation', 'analytics', 'events', 'tasks'].includes(route.module) && !['comparison', 'shifts', 'structure', 'rules', 'replay', 'losses'].includes(route.section);
  const notifications = tasks.filter(task => !task.done && (route.role === 'leader' || task.role === route.role));
  const navGroup = (modules: ModuleId[], label: string) => <div className="nav-group"><span className="nav-group-label">{label}</span>{modules.map(id => <a key={id} href={routeHash({ role: route.role, module: id, section: sectionsFor(route.role, id)[0]?.id ?? '' })} onClick={event => { if (id === 'quality' && route.module === 'quality') { event.preventDefault(); go({ role: route.role, module: 'home', section: '' }); } }} aria-current={route.module === id ? 'page' : undefined} className={`nav-link ${route.module === id ? 'active' : ''}`} title={isNavCollapsed ? (id === 'home' ? 'Обзор рабочего места' : moduleById[id].label) : undefined}><Icon name={moduleById[id].icon} size={19}/><span>{id === 'home' ? 'Обзор рабочего места' : moduleById[id].label}</span>{id === 'tasks' && notifications.length > 0 && <em>{notifications.length}</em>}</a>)}</div>;
  if (!securityReady) return <div className="security-login-page"><p>Открываем демонстрационный контур…</p></div>;
  if (!session) return <div className="security-login-page"><div className="security-login-card"><h1>Не удалось открыть рабочее место</h1><p>{securityError}</p><button onClick={() => window.location.reload()}>Повторить</button></div></div>;
  return <div className="app-shell"><a className="skip-link" href="#main-content" onClick={e => { e.preventDefault(); document.getElementById('main-content')?.focus(); }}>К содержимому</a>{mobileMenu && <button className="mobile-scrim" aria-label="Закрыть навигацию" onClick={() => setMobileMenu(false)}/>}
    <aside className={`sidebar ${mobileMenu ? 'is-open' : ''} ${isNavCollapsed ? 'is-collapsed' : ''}`}><a className="brand" href={routeHash({ role: route.role, module: route.role === 'controller' ? 'quality' : 'home', section: route.role === 'controller' ? 'signals' : '' })}><span className="brand-icon"><Icon name="orbit" size={34}/><i/></span><span><strong>ОРБИТА<span>.QC</span></strong><small>КАЧЕСТВО ВЫШЕ ОРБИТЫ</small></span></a><div className="workspace-identity"><span className="role-avatar">{role.initials}</span><div><small>РАБОЧЕЕ ПРОСТРАНСТВО</small><strong>{role.name}</strong></div><span className="status-dot"/></div><nav aria-label="Основная навигация">{navGroup(role.primary, 'РАБОТА')}{navGroup(role.secondary, route.role === 'administrator' ? 'ЗАЩИТА И РАСШИРЕНИЯ' : 'АНАЛИЗ И РАЗВИТИЕ')}</nav><div className="sidebar-bottom"><a href={routeHash({ role: route.role, module: 'guide', section: 'map' })} className={`nav-link ${route.module === 'guide' ? 'active' : ''}`} aria-current={route.module === 'guide' ? 'page' : undefined} title={isNavCollapsed ? 'Карта приложения' : undefined}><Icon name="guide" size={18}/><span>Карта приложения</span><Icon name="arrow" size={14}/></a><button type="button" className="sidebar-collapse-toggle" onClick={() => setIsNavCollapsed(value => !value)} aria-label={isNavCollapsed ? 'Развернуть меню' : 'Свернуть меню'} title={isNavCollapsed ? 'Развернуть меню' : 'Свернуть меню'}><span aria-hidden="true">{isNavCollapsed ? '▶' : '◀'}</span><span className="sidebar-collapse-label">{isNavCollapsed ? 'Развернуть' : 'Свернуть меню'}</span></button><div className="environment-mark"><span className="status-dot"/><span>УЧЕБНЫЙ КОНТУР<small>ОРБИТА.QC / 0.2</small></span><Icon name="orbit" size={22}/></div></div></aside>
    <div className="main-shell"><header className="topbar"><button className="icon-button mobile-toggle" aria-label="Открыть навигацию" aria-expanded={mobileMenu} onClick={() => setMobileMenu(!mobileMenu)}><Icon name="layer"/></button><div className="plant-context"><Icon name="production" size={19}/><span>Демонстрационная линия</span><span className="context-divider"/><span className="mono">01</span></div><button className="global-search" onClick={() => setOverlay('search')} aria-label="Открыть поиск"><Icon name="search" size={17}/><span>Найти в системе</span><kbd>Ctrl K</kbd></button><button className="icon-button notification-trigger" aria-label={`Уведомления: ${notifications.length}`} onClick={() => setOverlay('notifications')}><Icon name="bell" size={20}/>{notifications.length > 0 && <i/>}</button><div className="role-selector" ref={roleMenuRef}><button className="role-trigger" aria-expanded={roleMenu} onClick={() => setRoleMenu(!roleMenu)}><span className="role-avatar small">{role.initials}</span><span><strong>{role.name}</strong><small>Демонстрационный режим</small></span><Icon name="chevron" size={15}/></button>{roleMenu && <div className="role-popover"><div className="popover-title">Рабочее место<span>Переключить роль без входа</span></div>{roles.map(r => <button key={r.id} onClick={() => changeRole(r.id)} aria-pressed={route.role === r.id}><span className="role-avatar small">{r.initials}</span><span><strong>{r.name}</strong><small>{r.focus}</small></span>{route.role === r.id && <Icon name="check" size={17}/>}</button>)}</div>}</div></header>
      <main id="main-content" tabIndex={-1}><div className="breadcrumbs"><span>Рабочее место</span><Icon name="chevron" size={12}/><span>{role.name}</span>{route.module !== 'home' && <><Icon name="chevron" size={12}/><span>{workspace.label}</span></>}</div><div className="page-heading"><div><h1>{route.role === 'master' && route.module === 'operations' ? 'Пульт управления участком' : route.module === 'home' ? role.title : workspace.label}</h1><p>{route.role === 'master' && route.module === 'operations' ? 'Станки, операторы, доработка и очный досмотр по направлениям ОТК' : route.module === 'home' ? role.subtitle : workspace.caption}</p></div><div className="scope-controls">{route.module !== 'analytics' && <span className="date-label"><Icon name="clock" size={15}/>17–26 фев 2026</span>}{scopedView && <label><span className="sr-only">Фильтр смены</span><select aria-label="Фильтр смены" value={scope} onChange={e => setScope(e.target.value as Scope)}><option value="all">Все смены</option><option value="SHIFT-A">Смена А · 08:00–16:00</option><option value="SHIFT-B">Смена Б · 16:00–00:00</option></select></label>}</div></div>
        {sections.length > 1 && <nav className="tabs" aria-label={`Разделы: ${workspace.label}`}>{sections.map(section => <a key={section.id} href={routeHash({ role: route.role, module: route.module, section: section.id })} aria-current={route.section === section.id ? 'page' : undefined}>{section.label}{section.optional && <span className="tab-extra" title="Дополнительная возможность">+</span>}</a>)}</nav>}
        <WorkspaceView key={`${route.role}-${route.module}-${route.section}`} route={route} scope={scope} navigate={navigate} openItem={openItem} openCase={openCase} changeRole={changeRole}/>
        <footer><span><Icon name="orbit" size={15}/>ОРБИТА.QC <i/> Живой демопоток</span><span>Синтетические события · февраль 2026<button onClick={() => navigate('guide', 'help')}>О данных и возможностях<Icon name="arrow" size={13}/></button></span></footer>
      </main>
    </div>
    {overlay === 'search' && <SearchDialog role={route.role} navigate={navigate} openItem={openItem} onClose={() => setOverlay(null)}/>}
    {overlay === 'notifications' && <Modal title="Уведомления рабочего места" className="notifications-dialog" onClose={() => setOverlay(null)}><div className="drawer-header"><div><span className="eyebrow">{role.name}</span><h2>Центр внимания</h2></div><button className="icon-button" aria-label="Закрыть уведомления" onClick={() => setOverlay(null)}><Icon name="close"/></button></div><div className="notification-list">{notifications.length ? notifications.map(task => <button key={task.id} onClick={() => { setOverlay(null); if (task.caseId) openCase(task.item, task.caseId); else openItem(task.item); }}><span className="task-symbol amber"><Icon name="tasks"/></span><div><strong>{task.title}</strong><p>{task.item} · {task.event.event_id}</p></div><Icon name="arrow" size={16}/></button>) : <Empty title="Новых действий для роли нет" text="Уведомления о проверках, отклонениях и передаче работы будут собраны здесь."/>}</div><Note>Сейчас показаны основания для действий из учебного набора. Фоновая доставка уведомлений ещё не подключена.</Note></Modal>}
    {route.item && !(route.caseId && ((route.role === 'controller' && route.module === 'quality') || (route.role === 'technologist' && route.module === 'investigation'))) && <ProductDrawer key={`${route.item}-${route.role}-${route.caseId ?? ''}`} id={route.item} caseId={route.caseId} role={route.role} onRoleChange={nextRole => changeRole(nextRole)} onClose={() => { const returnRoute = passportReturn.current; passportReturn.current = null; go(returnRoute && returnRoute.role === route.role && returnRoute.module === route.module ? returnRoute : { ...route, item: undefined, caseId: undefined }); }}/>}
    {toast && <div className="toast" role="status"><Icon name="check"/>{toast}<button aria-label="Закрыть сообщение" onClick={() => setToast('')}><Icon name="close" size={15}/></button></div>}
  </div>;
}
