import { useState } from 'react';
import { replayQualityIncidents } from './data-quality';
import { Badge, Button, Panel } from './ui';
import { deliveryFor, events, ingestState, time } from './domain';

export function DataQualityView({ openItem }: { openItem: (id: string) => void }) {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('all');
  const [revision, setRevision] = useState(1);
  const rows = replayQualityIncidents(events).filter(row => (status==='all' || row.status===status) && `${row.event.source_id} ${row.event.event_id} ${row.packet} ${row.type}`.toLowerCase().includes(query.toLowerCase()));
  const actual = ingestState().outcomes;
  return <div className="stack"><Panel title="Инциденты доставки телеметрии" eyebrow="КОНТРОЛЬ ДОСТАВКИ И ЦЕЛОСТНОСТИ" action={<Button icon="flow" onClick={()=>setRevision(r=>r+1)}>Повторить проверку</Button>}><p className="panel-description">Проверка {revision}: задержка станка, повтор контроля и перестановка пакетов MES. Расчёт выполнен на отдельном расписании доставки событий ITEM-007. Исходный поток и решения не изменяются.</p><div className="workspace-toolbar"><label className="local-search"><input aria-label="Поиск инцидента" placeholder="Источник, событие или пакет…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Статус инцидента" value={status} onChange={e=>setStatus(e.target.value)}>{['all','Обработано','Отклонено','Нормализовано'].map(s=><option key={s} value={s}>{s==='all'?'Все статусы':s}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Время приёма</th><th>Источник</th><th>Тип инцидента</th><th>Исходный Event ID</th><th>Принятое действие</th><th>Статус</th></tr></thead><tbody>{rows.map(row=><tr key={row.packet}><td>{time(row.received)}:{new Date(row.received).getSeconds().toString().padStart(2,'0')}<small>событие {time(row.event.occurred_at)}</small></td><td>{row.event.source_id}</td><td>{row.type}</td><td><button className="cell-link" onClick={()=>openItem(row.event.item_id)}>{row.event.event_id}</button><small>пакет {row.packet}</small></td><td>{row.action}</td><td><Badge tone={row.tone}>{row.status}</Badge></td></tr>)}</tbody></table>{!rows.length && <p className="panel-description">Нет инцидентов по выбранным условиям.</p>}</div><details className="tech-review-history"><summary>Исходные сообщения сценария</summary>{rows.map(row=><pre key={row.packet}>{JSON.stringify({packet_id:row.packet,received_at:row.received,message:row.event},null,2)}</pre>)}</details></Panel><Panel title="Журнал локального приёма" eyebrow="РЕАЛЬНЫЕ РЕЗУЛЬТАТЫ ЛОКАЛЬНОГО ПРИЁМА">{actual.length ? <div className="table-wrap"><table><thead><tr><th>Доставка / приём</th><th>Event ID</th><th>Результат</th><th>Действие</th></tr></thead><tbody>{actual.map((row,i)=><tr key={`${row.delivery_id}-${i}`}><td>{row.delivery_id}<small>{deliveryFor(row.event_id) ? time(deliveryFor(row.event_id)!.deliver_at) : 'Нет в текущей проекции'}</small></td><td>{row.event_id}</td><td>{({accepted:'Принято',late:'Поздняя доставка',duplicate:'Точный дубль',error:'Ошибка'})[row.kind]}</td><td>{row.reason}</td></tr>)}</tbody></table></div>:<p className="panel-description">В этой локальной копии новые пакеты ещё не принимались. Результаты загрузки и воспроизведения появятся здесь.</p>}</Panel></div>;
}
