import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Badge, Button, Empty, Icon, ImagePreview, Note, ProductDrawing } from './ui';
import { moduleById, roleById, roles, sectionsFor, type ModuleId, type RoleId } from './navigation';
import { cases, catalogs, decisionNames, defectNames, deliveries, deliveryFor, describeEvent, eventNames, events, eventsFor, items, mediaFor, mediaUrl, operations, productStatus, resultNames, stationNames, tasks, time, type WorkflowAction } from './domain';
import { currentSecurityUser, securePerformAction } from './security-client';
import type { Navigate } from './views';
import { ControllerCaseContent } from './controller-ui';
import { ProductSpecificationBlock } from './product-specification';
import { IntegrationBadges } from './integration-badges';
import { productSpecification } from './product-catalog';
import { pendingEvidenceRequests } from './technologist-evidence';
import { secureRecordMasterProcessReport } from './security-client';

export function Modal({ title, children, onClose, className = '' }: { title: string; children: ReactNode; onClose: () => void; className?: string }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []);
  return <dialog ref={ref} aria-label={title} className={className} onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="dialog-content">{children}</div></dialog>;
}
function DraftForm({ item, role }: { item: string; role: RoleId }) {
  const own = eventsFor(item);
  const lastDecision = own.filter(e => e.event_type === 'quality_decision').at(-1);
  const lastMaster = own.filter(e => e.event_type === 'master_action').at(-1);
  const afterMaster = !!lastMaster && (!lastDecision || Date.parse(lastMaster.occurred_at) > Date.parse(lastDecision.occurred_at));
  const options: [WorkflowAction, string][] = role === 'master' ? [['master_complete', item === 'ITEM-015' || item === 'ITEM-016' ? 'Провести очную проверку и добавить фото' : 'Завершить работу и передать на контроль']]
    : role === 'technologist' ? [['hypothesis', 'Записать гипотезу'], ['cause_confirm', 'Установить причину']]
    : item === 'ITEM-015' && lastDecision?.data.disposition === 'quarantine' ? [['scrap', 'Решить о списании']]
    : afterMaster ? item === 'ITEM-015' ? [['confirm', 'Подтвердить критический дефект'], ['additional', 'Запросить ещё проверку']] : item === 'ITEM-016' ? [['reject', 'Отклонить исходный признак'], ['confirm', 'Подтвердить дефект']] : item === 'ITEM-014' && own.filter(e => e.event_type === 'master_action').length === 1 ? [['recheck_fail', 'Заусенец остался: новый круг'], ['release', 'Выпустить после проверки']] : [['release', 'Повторный контроль: выпустить'], ['recheck_fail', 'Дефект остался: новый круг']]
    : lastDecision ? [['additional', 'Запросить доппроверку'], ['confirm', 'Подтвердить признак'], ['reject', 'Отклонить признак']]
    : own.some(e => e.data.inspection_result === 'unable_to_assess') ? [['additional', 'Запросить доппроверку'], ['confirm', 'Подтвердить признак']] : [['confirm', 'Подтвердить признак'], ['additional', 'Запросить доппроверку'], ['reject', 'Отклонить признак']];
  const [outcome, setOutcome] = useState<WorkflowAction>(options[0][0]);
  const [reason, setReason] = useState('');
  const [includePhoto, setIncludePhoto] = useState(true);
  const [status, setStatus] = useState('');
  return <form className="draft-form" onSubmit={async e => { e.preventDefault(); try { await securePerformAction(item, role, outcome, reason.trim(), includePhoto); setStatus('Событие записано. Задачи и показатели обновлены.'); setReason(''); } catch (error) { setStatus(error instanceof Error ? error.message : 'Не удалось записать событие'); } }}><div className="section-title"><h3>{role === 'controller' ? 'Зафиксировать решение' : role === 'technologist' ? 'Записать заключение' : 'Зафиксировать выполнение'}</h3><Badge tone="blue">Живое действие</Badge></div><label>Действие<select value={outcome} onChange={e => { setOutcome(e.target.value as WorkflowAction); setStatus(''); }}>{options.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Исполнитель / автор<input value={currentSecurityUser()?.id ?? ''} readOnly /></label><label>Основание, результат и комментарий<textarea value={reason} onChange={e => setReason(e.target.value)} required minLength={5} maxLength={4000} placeholder="Укажите факты, ограничения и выполненное действие…" rows={4}/></label>{role === 'master' && ['ITEM-013', 'ITEM-014', 'ITEM-015', 'ITEM-016', 'ITEM-025', 'ITEM-028'].includes(item) && <label className="photo-choice"><input type="checkbox" checked={includePhoto} disabled={item === 'ITEM-015'} onChange={e => setIncludePhoto(e.target.checked)}/>Прикрепить учебное фото результата</label>}{role === 'master' && <p className="helper-text">Фото появляется в истории только после записи выполнения мастера. Фото не измеряет допуск.</p>}<button className="button primary" disabled={reason.trim().length < 5} type="submit">Записать событие<Icon name="check" size={16}/></button><span className="form-status" role="status">{status}</span></form>;
}

function MediaEvidence({ id }: { id: string }) {
  const evidence = mediaFor(id);
  if (!evidence.length) return <Note tone="amber">Кадр недоступен. Для этого изделия изображение ещё не поступило; по фото нельзя делать вывод о годности.</Note>;
  return <div className="evidence-grid">{evidence.map(({ event, asset }) => <figure key={`${event.event_id}-${asset.asset_id}`} className="evidence-card"><ImagePreview src={mediaUrl(asset)} alt={asset.description} title={asset.description}/><figcaption><strong>{asset.stage === 'before_machine' ? 'До станка' : asset.stage === 'before_rework' || asset.stage === 'after_machine' ? 'После станка' : asset.stage === 'ambiguous_observation' ? 'Сомнительный кадр CV' : asset.stage === 'additional_check' ? 'Доппроверка' : 'После доработки'} · {asset.capture_source === 'fixed_camera' ? 'Камера CV' : 'Фото мастера'}</strong><span>{time(event.occurred_at)} · качество: {event.data.observation_quality === 'poor' ? 'ограничено' : event.data.observation_quality === 'good' ? 'достаточное' : 'не указано'}</span><p>{asset.description}</p></figcaption></figure>)}</div>;
}

function StateStrip({ id }: { id: string }) {
  const own = eventsFor(id);
  const observation = own.filter(e => e.event_type === 'inspection_result').at(-1);
  const decision = own.filter(e => e.event_type === 'quality_decision').at(-1);
  const master = own.filter(e => e.event_type === 'master_action').at(-1);
  const operation = operations.filter(op => op.item === id).at(-1);
  const task = tasks.find(t => t.item === id && t.role === 'master');
  const cause = own.filter(e => e.event_type === 'cause_review').at(-1);
  return <dl className="state-strip"><div><dt>Наблюдение</dt><dd>{observation ? resultNames[observation.data.inspection_result ?? ''] : 'Нет результата'}</dd></div><div><dt>Решение ОТК</dt><dd>{decision ? decisionNames[decision.data.decision ?? ''] : 'Не принято'}</dd></div><div><dt>Удержание / доработка</dt><dd>{decision?.data.disposition === 'rework' ? 'Доработка' : decision?.data.disposition === 'hold' ? 'Удержано' : decision?.data.disposition === 'quarantine' ? 'Карантин' : decision?.data.disposition === 'release' ? 'Снято' : 'Нет решения'}</dd></div><div><dt>Операция</dt><dd>{operation ? operation.end ? 'Завершена' : operation.paused ? 'Пауза' : 'В работе' : 'Не поступала'}</dd></div><div><dt>Задача мастера</dt><dd>{task ? 'Открыта' : master ? 'Выполнена' : 'Не назначена'}</dd></div><div><dt>Причина</dt><dd>{cause?.data.status === 'confirmed' ? 'Установлена' : cause ? 'Гипотеза' : 'Не установлена'}</dd></div></dl>;
}

function MasterProcessForm({ item, initialCaseId }: { item: string; initialCaseId?: string }) {
  const confirmed = cases.filter(record => record.item === item && record.confirmed);
  const [caseId, setCaseId] = useState(initialCaseId ?? confirmed[0]?.id ?? '');
  const [operationRunId, setOperationRunId] = useState('');
  const [fixtureCondition, setFixtureCondition] = useState<'checked' | 'issue' | 'unknown' | 'not_applicable'>('unknown');
  const [toolCondition, setToolCondition] = useState<'checked' | 'issue' | 'unknown' | 'not_applicable'>('unknown');
  const [setupChanged, setSetupChanged] = useState<'yes' | 'no' | 'unknown'>('unknown');
  const [comment, setComment] = useState('');
  const [notice, setNotice] = useState('');
  const [requestId, setRequestId] = useState('');
  const runs = eventsFor(item).filter(event => event.event_type === 'operation_started');
  const selected = confirmed.find(record => record.id === caseId);
  const requests = selected ? pendingEvidenceRequests(selected).filter(event => event.data.recipient_role === 'master') : [];
  const answering = requests.find(event => event.event_id === requestId) ?? requests.at(-1);
  if (!confirmed.length) return <Note>Сведения об операции можно привязать после подтверждения дефекта контролёром.</Note>;
  return <div className="master-process-form"><div className="section-title"><h3>Сведения технологу об операции</h3><Badge tone="blue">Отдельная запись мастера</Badge></div><p className="helper-text">Зафиксируйте лично проверенные обстоятельства. Данные MES и станка останутся отдельными источниками.</p>{answering && <Note tone="amber">Технолог запросил: {answering.data.reason}</Note>}
    <form onSubmit={async event => { event.preventDefault(); try { await secureRecordMasterProcessReport({ caseId, operationRunId, fixtureCondition, toolCondition, setupChanged, comment, actor: currentSecurityUser()?.id ?? '', requestId: answering?.event_id }); setNotice('Сведения сохранены в общей истории.'); setComment(''); } catch (error) { setNotice(error instanceof Error ? error.message : 'Не удалось сохранить сведения'); } }}>
      <label>Подтверждённый случай<select value={caseId} onChange={event => { setCaseId(event.target.value); setRequestId(''); }}>{confirmed.map(record => <option key={record.id} value={record.id}>{defectNames[record.type]} · {record.id}</option>)}</select></label>
      {requests.length > 0 && <label>Ответ на запрос<select value={answering?.event_id ?? ''} onChange={event => setRequestId(event.target.value)}>{requests.map(request => <option key={request.event_id} value={request.event_id}>{request.data.reason}</option>)}</select></label>}
      <label>Операция<select value={operationRunId} onChange={event => setOperationRunId(event.target.value)}><option value="">Нет связанной операции / входной дефект</option>{runs.map(run => <option key={run.event_id} value={run.operation_run_id}>{run.operation_run_id} · {time(run.occurred_at)}</option>)}</select></label>
      <div className="master-process-pair"><label>Оснастка<select value={fixtureCondition} onChange={event => setFixtureCondition(event.target.value as typeof fixtureCondition)}><option value="unknown">Не проверена</option><option value="checked">Проверена, отклонений нет</option><option value="issue">Замечено отклонение</option><option value="not_applicable">Не относится</option></select></label><label>Инструмент<select value={toolCondition} onChange={event => setToolCondition(event.target.value as typeof toolCondition)}><option value="unknown">Не проверен</option><option value="checked">Проверен, отклонений нет</option><option value="issue">Замечено отклонение</option><option value="not_applicable">Не относится</option></select></label></div>
      <label>Наладка менялась<select value={setupChanged} onChange={event => setSetupChanged(event.target.value as typeof setupChanged)}><option value="unknown">Неизвестно</option><option value="no">Нет</option><option value="yes">Да</option></select></label>
      <label>Что фактически проверено<textarea value={comment} onChange={event => setComment(event.target.value)} rows={4} placeholder="Факт, время проверки, результат"/></label><button className="button primary" type="submit" disabled={comment.trim().length < 8}>Передать сведения<Icon name="arrow" size={16}/></button><span role="status" className="form-status">{notice}</span>
    </form></div>;
}

export function ProductDrawer({ id, caseId, role, onClose, onRoleChange }: { id: string; caseId?: string; role: RoleId; onClose: () => void; onRoleChange: (role: RoleId) => void }) {
  const [section, setSection] = useState('overview');
  const [showPassport, setShowPassport] = useState(false);
  const product = items.find(item => item.id === id);
  const own = eventsFor(id); const ownCases = cases.filter(c => c.item === id); const status = productStatus(id);
  const routeStations = catalogs.stations.filter(station => station.id.endsWith('-02') === (own[0]?.line_id === 'LINE-02'));
  const tabs = [['overview', 'Обзор'], ['timeline', 'История'], ['observations', 'Наблюдения'], ['decisions', 'Решения'], ['structure', 'Состав']];
  if (role === 'master') tabs.push(['process', 'Сведения технологу']);
  if (role === 'administrator' || role === 'technologist') tabs.push(['source', 'Исходные события']);
  if (role === 'controller' && product && ownCases.length && !showPassport && caseId) return <Modal title={`Заявка контролёра ${id}`} className="drawer controller-dossier" onClose={onClose}><ControllerCaseContent item={id} caseId={caseId} onClose={onClose} onPassport={() => setShowPassport(true)} onRoleChange={onRoleChange}/></Modal>;
  return <Modal title={`Паспорт изделия ${id}`} className="drawer product-passport" onClose={onClose}><div className="drawer-header"><div><span className="eyebrow">ЕДИНЫЙ ПАСПОРТ ИЗДЕЛИЯ</span><h2 className="mono">{id}</h2><p>{productSpecification(id).name} · {product?.work_order_id ?? 'Неизвестный заказ'}</p></div><button className="icon-button" aria-label="Закрыть паспорт" onClick={onClose}><Icon name="close" size={22}/></button></div>{!product ? <Empty title="Изделие не найдено" text="В учебном наборе нет изделия с таким идентификатором." action={<Button onClick={onClose}>Вернуться</Button>}/> : <><div className="drawer-summary"><Badge tone={status.tone}>{status.label}</Badge><span>{own.length} событий</span><span>Ревизия {product.assembly_revision}</span>{role === 'controller' && ownCases.length > 0 && <button className="text-button" onClick={() => setShowPassport(false)}>Вернуться к заявке</button>}</div><label className="drawer-role-preview">Посмотреть это изделие в роли<select aria-label="Роль в карточке изделия" value={role} onChange={e => onRoleChange(e.target.value as RoleId)}>{roles.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select><small>Демонстрация рабочих мест</small></label><div className="tabs drawer-tabs" role="tablist" aria-label="Разделы паспорта">{tabs.map(([key, label]) => <button role="tab" aria-selected={section === key} aria-controls="product-tab-content" id={`product-tab-${key}`} key={key} onClick={() => setSection(key)}>{label}</button>)}</div><div className="drawer-body" role="tabpanel" id="product-tab-content" aria-labelledby={`product-tab-${section}`}>
    {section === 'overview' && <><div className="product-overview"><div><ProductDrawing/><ProductSpecificationBlock item={id}/><IntegrationBadges item={id}/></div><dl className="facts"><div><dt>Заказ</dt><dd className="mono">{product.work_order_id}</dd></div><div><dt>Обозначение ЕСКД</dt><dd>{productSpecification(id).designation}</dd></div><div><dt>Узел</dt><dd>{productSpecification(id).assembly}</dd></div><div><dt>Компоненты</dt><dd>{product.components.length}</dd></div><div><dt>Случаи качества</dt><dd>{ownCases.length}</dd></div><div><dt>Источники</dt><dd>{new Set(own.map(e => e.source_id)).size}</dd></div></dl></div><StateStrip id={id}/><h3 className="small-heading">Визуальные основания · до / после</h3><MediaEvidence id={id}/><h3 className="small-heading">Маршрут изделия</h3><div className="product-route">{routeStations.map(station => { const stationEvents = own.filter(e => e.station_id === station.id); return <button key={station.id} onClick={() => setSection('timeline')}><Icon name={stationEvents.length ? 'check' : 'dot'}/><strong>{station.name}</strong><small>{stationEvents.length ? `${stationEvents.length} событий в истории` : 'Событий нет'}</small></button>; })}</div><h3 className="small-heading">Качество и основания</h3>{ownCases.length ? ownCases.map(c => <div className="case-detail" key={c.id}><div className="section-title"><strong>{defectNames[c.type]} <span className="mono text-sub">{c.id}</span></strong><Badge tone={c.tone}>{c.status}</Badge></div><p>{c.observations.length} набл. · {c.region} · {c.component}</p><div className="cause-note"><Icon name="investigation"/><div><strong>{c.review?.data.status === 'confirmed' ? 'Причина установлена' : c.review ? 'Гипотеза технолога' : 'Причина не установлена'}</strong><p>{c.review?.data.reason ?? 'В истории нет подтверждённого заключения о причине.'}</p></div></div><button className="text-button" onClick={() => setSection('observations')}>Посмотреть наблюдения<Icon name="arrow" size={15}/></button></div>) : <Note tone="green">Случаи дефектов пока не зарегистрированы. Оценка годности требует отдельного контрольного результата.</Note>}<div className="drawer-actions"><Button onClick={() => setSection('timeline')}>Вся хронология</Button>{['controller', 'master'].includes(role) && <Button primary onClick={() => setSection('decisions')}>Записать действие</Button>}{role === 'technologist' && caseId && <Button primary onClick={onClose}>Вернуться к делу</Button>}</div></>}
    {section === 'timeline' && <><Note>Хронология упорядочена по времени события. Время доставки хранится отдельно, запоздавшие события сохраняют своё место в процессе.</Note><div className="timeline">{own.map(e => <div className="timeline-entry" key={e.event_id}><span className={`timeline-dot ${e.event_type === 'quality_decision' ? 'blue' : ''}`}/><div className="timeline-meta"><span className="mono">{time(e.occurred_at)}</span><span>{eventNames[e.event_type]}</span></div><h3>{e.event_type === 'quality_decision' ? decisionNames[e.data.decision!] : stationNames[e.station_id]}</h3><p>{describeEvent(e)}</p><small className="mono">{e.event_id} · {e.source_id}{e.actor_id ? ` · ${e.actor_id}` : ''} · доставка {deliveryFor(e.event_id) ? time(deliveryFor(e.event_id)!.deliver_at) : '—'}</small></div>)}</div></>}
    {section === 'observations' && <><Note>Фото подтверждает только видимое состояние. Размерный допуск для ITEM-013 подтверждается отдельным ручным замером.</Note><MediaEvidence id={id}/><div className="observation-list">{own.filter(e => e.event_type === 'inspection_result').map(e => <article key={e.event_id} className="observation-card"><div className="section-title"><span className="mono">{e.event_id} / {time(e.occurred_at)}</span><Badge tone={e.data.observation_quality === 'poor' ? 'amber' : 'blue'}>{e.data.observation_quality === 'poor' ? 'Плохой обзор' : 'Достаточный обзор'}</Badge></div><h3>{stationNames[e.station_id]}</h3><strong>{resultNames[e.data.inspection_result!]}</strong><div className="field-tags">{e.data.defects?.map(f => <span key={f.finding_id}>{defectNames[f.defect_type_id]} · {f.region}</span>)}</div><dl className="facts"><div><dt>Источник</dt><dd className="mono">{e.source_id}</dd></div><div><dt>Уверенность источника</dt><dd>{e.data.confidence == null ? 'Не указана' : `${Math.round(e.data.confidence * 100)}%`}</dd></div><div><dt>Метод</dt><dd>{e.data.method === 'external_analyzer' ? 'Внешний анализатор' : 'Ручной контроль'}</dd></div></dl></article>)}</div></>}
    {section === 'decisions' && <><h3 className="small-heading">Ранее записанные действия</h3>{own.filter(e => ['quality_decision', 'cause_review', 'master_action', 'technical_disposition', 'manual_measurement'].includes(e.event_type)).length ? own.filter(e => ['quality_decision', 'cause_review', 'master_action', 'technical_disposition', 'manual_measurement'].includes(e.event_type)).map(e => <div key={e.event_id} className="decision-entry"><div className="section-title"><strong>{e.event_type === 'quality_decision' ? decisionNames[e.data.decision!] : eventNames[e.event_type]}</strong><span className="mono">{time(e.occurred_at)}</span></div><p>{e.data.reason}</p><small className="mono">{e.actor_id} · {e.event_id}</small><div className="field-tags">{(e.data.finding_refs ?? e.data.basis_event_ids)?.map(ref => <span key={ref}>{ref}</span>)}</div></div>) : <Empty title="Записанных решений нет" text="Наблюдения и отсутствие решения показаны независимо."/>}{['controller', 'master'].includes(role) ? <DraftForm key={`${id}-${role}`} item={id} role={role}/> : <Note>{role === 'technologist' ? 'Заключение по причине оформляется в рабочем месте «Разбор причин» с привязкой к конкретному делу.' : 'Это рабочее место предназначено для просмотра оснований и результатов.'}</Note>}</>}
    {section === 'structure' && <><ProductDrawing/><div className="assembly-tree"><div><Icon name="box"/><strong>{id} · ревизия A</strong></div>{product.components.map(component => <div className="tree-child" key={component.id}><Icon name="products"/><div><strong>{component.component_type_id === 'BODY' ? 'Корпус' : component.component_type_id === 'INSERT' ? 'Вставка' : 'Крепёж'}</strong><small className="mono">{component.id}</small></div></div>)}</div><Note>Условная схема показывает состав. Реальная CAD-геометрия в наборе отсутствует.</Note></>}
    {section === 'process' && role === 'master' && <MasterProcessForm item={id} initialCaseId={caseId}/>}
    {section === 'source' && <><Note>Это исходные сообщения учебного набора. В рабочем контуре оригиналы должны храниться неизменяемо и отдельно от представлений.</Note>{own.map(e => <details className="source-event" key={e.event_id}><summary><span className="mono">{e.event_id}</span> {eventNames[e.event_type]}<span className="text-sub">{deliveries.filter(d => d.message.event_id === e.event_id).length} доставок</span></summary><pre>{JSON.stringify(e, null, 2)}</pre></details>)}</>}
  </div></>}</Modal>;
}

export function SearchDialog({ role, navigate, openItem, onClose }: { role: RoleId; navigate: Navigate; openItem: (id: string) => void; onClose: () => void }) {
  const [query, setQuery] = useState(''); const q = query.trim().toLowerCase();
  const entries = [...roleById[role].primary, ...roleById[role].secondary, 'guide' as ModuleId].flatMap(id => [{ key: id, title: moduleById[id].label, description: moduleById[id].caption, icon: moduleById[id].icon, action: () => navigate(id) }, ...sectionsFor(role, id).map(section => ({ key: `${id}-${section.id}`, title: section.label, description: moduleById[id].label, icon: moduleById[id].icon, action: () => navigate(id, section.id) }))]);
  const entityEntries = [...items.map(item => ({ key: item.id, title: item.id, description: `Кронштейн · ${item.work_order_id}`, icon: 'products', action: () => openItem(item.id) })), ...cases.map(c => ({ key: c.id, title: c.id, description: `${defectNames[c.type]} · ${c.item}`, icon: 'quality', action: () => openItem(c.item) })), ...events.map(event => ({ key: event.event_id, title: event.event_id, description: `${eventNames[event.event_type]} · ${event.item_id}`, icon: 'events', action: () => openItem(event.item_id) }))];
  const results = (q ? [...entries, ...entityEntries].filter(entry => `${entry.title} ${entry.description}`.toLowerCase().includes(q)) : entries.filter(entry => !entry.key.includes('-'))).slice(0, 14);
  return <Modal title="Поиск по приложению" onClose={onClose} className="search-dialog"><div className="command-input"><Icon name="search" size={22}/><input autoFocus placeholder="Раздел, изделие, случай или событие…" aria-label="Поиск по приложению" value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && results[0]) { onClose(); results[0].action(); } }}/><button className="kbd-button" onClick={onClose}>Esc</button></div><div className="search-heading">{q ? 'Результаты поиска' : 'Перейти к рабочей области'}<span>{roleById[role].name}</span></div><div className="command-results">{results.map(result => <button key={result.key} onClick={() => { onClose(); result.action(); }}><span className="search-result-icon"><Icon name={result.icon}/></span><span><strong>{result.title}</strong><small>{result.description}</small></span><Icon name="arrow" size={16}/></button>)}{!results.length && <Empty title="Ничего не найдено" text="Попробуйте номер ITEM-007 или название раздела."/>}</div><div className="command-footer"><span><kbd>Enter</kbd> открыть первый результат</span><span><kbd>Esc</kbd> закрыть</span></div></Modal>;
}
