import { useEffect, useState } from 'react';
import { Bar, CartesianGrid, ComposedChart, Legend, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Badge, Button, Icon, Metric, Note, Panel } from './ui';
import { pendingExecutiveActions, readExecutiveApprovals, loadExecutiveApprovals, signExecutiveAction, verifyExecutiveApproval, type ExecutiveApproval } from './manager-decisions';
import { PersonnelView, RepairBalanceView } from './executive-people-views';
import { ExecutiveReportGenerator } from './executive-report-view';
import { defectTypes, equipmentFleet, executiveActions, executiveKpis, managerSnapshot, operationDurations, orderRisks, paretoFor, productionAreas, qualityTrend, recurrenceFor, rootCauseDistribution, timeLosses, type DefectOrigin } from './managerMockData';
import type { ViewProps } from './views';
import './production-head.css';

const number = (value: number) => value.toLocaleString('ru-RU', { maximumFractionDigits: 1 });
const percent = (value: number) => `${number(value)}%`;
const lossTotal = timeLosses.reduce((sum, row) => sum + row.hours, 0);
const causeTotal = rootCauseDistribution.reduce((sum, row) => sum + row.count, 0);

function CommandCenter({ navigate, openItem }: ViewProps) {
  const [selected, setSelected] = useState('mill');
  const area = productionAreas.find(row => row.id === selected)!;
  return <>
    <div className="metric-grid">
      <Metric label="Прохождение с первого раза · FTR" value={percent(executiveKpis.ftr)} note={`↑ ${number(executiveKpis.ftr - managerSnapshot.previousFtr)} п.п. к январю · цель >95%`} icon="quality" tone="amber" onClick={() => document.getElementById('enterprise-pareto')?.scrollIntoView({ behavior: 'smooth' })}/>
      <Metric label="Выполнение программы" value={percent(executiveKpis.programCompletion)} note={`${managerSnapshot.released} из ${managerSnapshot.productionPlan} плановых единиц · MES / 1С`} icon="production" tone="green"/>
      <Metric label="КТГ оборудования" value={percent(executiveKpis.fleetAvailability)} note={`Весь парк предприятия · ${managerSnapshot.fleetCount} единиц оборудования`} icon="cpu" tone="amber"/>
      <Metric label="Окончательный брак" value={percent(executiveKpis.finalScrap)} note={`${managerSnapshot.finalScrap} из ${managerSnapshot.checked} проверенных · лимит <1,5%`} icon="lock" tone="red" onClick={() => navigate('executive', 'balance')}/>
    </div>
    <div className="ph-summary-strip"><span><strong>{percent(executiveKpis.finalScrap)}</strong> окончательный брак <Badge tone="green">Лимит &lt;1,5%</Badge></span><span><strong>{number(executiveKpis.reworkHours)} н·ч</strong> доработки</span><span><strong>{percent(executiveKpis.programCompletion)}</strong> программа MES / 1С</span></div>
    <Panel title="Состояние производственной программы" eyebrow="1С:ERP / MES · ЗАКАЗЧИК: РОСКОСМОС" action={<Badge tone="blue">Демонстрационная сводка</Badge>}>
      <div className="ph-order-grid">{orderRisks.map(order => <article key={order.id} className={`ph-order ${order.tone}`}>
        <div className="ph-card-top"><span className="mono">{order.id}</span><Badge tone={order.tone}>{order.status}</Badge></div>
        <h3>{order.name}</h3><div className="ph-order-value"><strong>{order.released}<small> / {order.plan}</small></strong><span>Выпущено · сдача {order.due}</span></div>
        <div className="ph-progress" role="progressbar" aria-label={`Выпуск ${order.id}`} aria-valuemin={0} aria-valuemax={order.plan} aria-valuenow={order.released}><span style={{ width: `${order.released / order.plan * 100}%` }}/></div>
        <div className="ph-card-top"><span>Выход годного: <strong>{percent(order.accepted / order.inspected * 100)}</strong></span><span>{order.delayShifts ? `Риск: +${number(order.delayShifts)} смены` : 'Риск срока: низкий'}</span></div>
        <p>{order.reason}</p>{order.item && <Button onClick={() => openItem(order.item!)}>Паспорт {order.item}</Button>}
      </article>)}</div><p className="ph-caption">Две приоритетные партии из месячной программы 1 000 шт. План и сроки — учебный снимок 1С; выпуск — учебный снимок MES / ОТК. Названия заказов заданы для управленческого сценария.</p>
    </Panel>
    <Panel title="Тепловая карта участков" eyebrow="КАЧЕСТВО И ПОВТОРНАЯ ОБРАБОТКА">
      <div className="ph-area-grid">{productionAreas.map(row => <button key={row.id} className={`ph-area ${row.tone} ${selected === row.id ? 'selected' : ''}`} aria-pressed={selected === row.id} onClick={() => setSelected(row.id)}><span className="ph-card-top"><Icon name={row.tone === 'green' ? 'check' : 'alert'}/><span>{row.state}</span></span><strong>{row.label}</strong><span>FTR {percent(row.ftr)}</span><small>Доработки: {number(row.lossHours)} н·ч</small></button>)}</div>
      <div className="ph-area-detail" aria-live="polite"><div><h3>{area.label}</h3><p>{area.detail}</p></div><div className="ph-inline-actions">{area.item && <Button onClick={() => openItem(area.item!)}>Паспорт {area.item}</Button>}<Button onClick={() => navigate('executive', area.next)}>Открыть {area.next === 'actions' ? 'решения' : 'баланс ремонтов'}</Button></div></div>
      <p className="ph-caption">Зелёный — норма; янтарный — задержки; красный — повторяющийся дефект. FTR участков имеет собственные знаменатели и не складывается в FTR цеха.</p>
    </Panel>
    <details className="ph-definitions"><summary>Как рассчитаны показатели</summary><p>FTR: 924 / 1 000 проверенных изделий. Из остальных 76 изделий: 65 направлены на доработку, 11 — окончательный брак. После доработки 24 приняты ОТК, 16 в изоляторе, 25 в работе. Годный выпуск: 924 + 24 = 948. Программа: 948 / 1 000 плановых единиц. КТГ всего парка: (3 200 − 345,6) / 3 200 = 89,2%. В подробной таблице показаны три критичных единицы из десяти. Доработки: сумма нормированного времени повторных операций; простои учитываются отдельно. Лимиты — условия учебного сценария.</p></details>
  </>;
}

function ParetoView({ openItem }: ViewProps) {
  const [origin, setOrigin] = useState<DefectOrigin>('all');
  const data = paretoFor(origin), rows = recurrenceFor(origin);
  const total = data.reduce((sum, row) => sum + row.count, 0);
  return <>
    <div className="ph-filter"><span>Происхождение дефекта</span><div className="filter-chips">{([['all', 'Все дефекты'], ['incoming', 'Входные · поставщики'], ['production', 'Производственные']] as const).map(([id, label]) => <button key={id} aria-pressed={origin === id} className={origin === id ? 'active' : ''} onClick={() => setOrigin(id)}>{label}</button>)}</div><Badge tone="blue">{total} подтверждённых дефектов</Badge></div>
    <Panel title="Парето по типам дефектов" eyebrow="ЧАСТОТА И НАКОПЛЕННАЯ ДОЛЯ">
      <div className="ph-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{ top: 15, right: 10, bottom: 25, left: 0 }}><CartesianGrid stroke="#334155" vertical={false}/><XAxis dataKey="label" tick={{ fill: '#cbd5e1', fontSize: 11 }} interval={0} height={55} tickFormatter={label => String(label).replace('Вмятины заготовок', 'Вмятины').replace('Царапины покрытия', 'Царапины').replace('Отклонение соосности', 'Соосность')}/><YAxis yAxisId="count" allowDecimals={false} tick={{ fill: '#94a3b8', fontSize: 11 }}/><YAxis yAxisId="share" orientation="right" domain={[0, 100]} unit="%" tick={{ fill: '#94a3b8', fontSize: 11 }}/><Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #475569', borderRadius: 10, color: '#f1f5f9' }} formatter={(value, name) => [name === 'Накопленная доля, %' ? percent(Number(value)) : value, name]}/><Legend wrapperStyle={{ fontSize: 12 }}/><ReferenceLine yAxisId="share" y={80} stroke="#64748b" strokeDasharray="4 4" label={{ value: '80%', fill: '#94a3b8', fontSize: 10 }}/><Bar yAxisId="count" dataKey="count" name="Подтверждённые дефекты" fill={origin === 'incoming' ? '#38bdf8' : '#fbbf24'} radius={[5, 5, 0, 0]}/><Line yAxisId="share" dataKey="cumulative" name="Накопленная доля, %" stroke="#cbd5e1" strokeWidth={2} dot={{ r: 4 }} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div>
      <div className="table-wrap"><table><caption className="sr-only">Числовые значения диаграммы Парето</caption><thead><tr><th>Дефект</th><th>Количество</th><th>Накопленная доля</th></tr></thead><tbody>{data.map(row => <tr key={row.id}><td>{row.label}</td><td>{row.count}</td><td>{percent(row.cumulative)}</td></tr>)}</tbody></table></div>
    </Panel>
    <Panel title="Матрица повторяемости" eyebrow="ОБОРУДОВАНИЕ / СМЕНА / ДЕФЕКТ"><div className="table-wrap"><table className="ph-matrix"><thead><tr><th>Оборудование / контроль</th><th>Смена</th>{defectTypes.map(type => <th key={type.id}>{type.label}</th>)}<th>Итого</th></tr></thead><tbody>{rows.map(row => <tr key={`${row.equipment}-${row.shift}`}><td className="mono">{row.equipment}</td><td>{row.shift}</td>{defectTypes.map(type => <td key={type.id}><span className={row.counts[type.id] >= 20 ? 'ph-heat high' : row.counts[type.id] >= 5 ? 'ph-heat medium' : 'ph-heat'}>{row.counts[type.id]}</span></td>)}<td>{Object.values(row.counts).reduce((sum, count) => sum + count, 0)}</td></tr>)}</tbody></table></div><p className="ph-caption">Единица учёта — подтверждённый дефект. Повторные наблюдения одного дефекта исключены. Срез меняет одновременно Парето и матрицу.</p></Panel>
    {origin !== 'incoming' && <Note tone="amber" icon="alert"><strong>75% заусенцев: EQ-CNC-01, 2-я смена.</strong> 30 из 40 случаев — устойчивая концентрация. Совпадение с вибропредупреждением поддерживает аппаратную гипотезу; вывод по конкретному изделию требует заключения технолога. <button className="cell-link" onClick={() => openItem('ITEM-007')}>Открыть ITEM-007 →</button></Note>}
    <div className="two-columns"><Panel title="Раздельный учёт причин" eyebrow="100 ДЕФЕКТОВ · МЕСЯЧНАЯ СВОДКА"><div className="ph-cause-bar" aria-hidden="true">{rootCauseDistribution.map(row => <span key={row.id} style={{ width: `${row.count / causeTotal * 100}%`, background: row.color }}/>)}</div><div className="ph-cause-list">{rootCauseDistribution.map(row => <div key={row.id}><i style={{ background: row.color }}/><span>{row.label}<small>{row.status}</small></span><strong>{percent(row.count / causeTotal * 100)}</strong></div>)}</div><p className="ph-caption">38 входных и 62 производственных дефекта; из производственных: 42 — оборудование, 12 — подтверждённые нарушения, 8 — причина не установлена. Классификация причин относится к архивной сводке и не подтверждает причину текущего дела ITEM-007.</p></Panel><Panel title="Динамика FTR" eyebrow="СОПОСТАВИМЫЕ МЕСЯЧНЫЕ СРЕЗЫ"><div className="ph-trends">{qualityTrend.map(row => <div key={row.label}><span>{row.label}</span><strong>{percent(row.firstPass / row.checked * 100)}</strong><div className="ph-progress"><span style={{ width: `${row.firstPass / row.checked * 100}%` }}/></div><small>{row.firstPass} с первого раза / {row.checked} проверено</small></div>)}</div><Note tone="amber">Рост +1,6 п.п.; до порога 95% не хватает 2,6 п.п. Первоочередная мера — диагностика EQ-CNC-01.</Note></Panel></div>
  </>;
}

function EquipmentView({ navigate }: ViewProps) {
  return <><div className="metric-grid ph-three-metrics"><Metric label="Плановый фонд парка" value="960 ч" note="3 единицы × 320 ч за месяц" icon="clock"/><Metric label="Простои и ожидания" value={`${number(lossTotal)} ч`} note="Фактические часы · отдельно от нормо-часов доработки" icon="alert" tone="amber"/><Metric label="Потери на доработки" value={`${number(executiveKpis.reworkHours)} н·ч`} note="65 повторных обработок · норма маршрута" icon="production" tone="amber"/></div>
    <Panel title="Надёжность парка оборудования" eyebrow="КТГ / MTBF / OEE"><div className="table-wrap"><table><thead><tr><th>Оборудование</th><th>КТГ</th><th>MTBF, ч</th><th>OEE</th><th>Вибронагрузка</th><th>Состояние</th></tr></thead><tbody>{equipmentFleet.map(row => <tr key={row.id} className={row.maintenance ? 'ph-warning-row' : ''}><td><strong className="mono">{row.id}</strong><small>{row.name}</small></td><td>{percent(row.availability)}</td><td>{number(row.mtbf)}<small>{row.failures} отказ(а) · {number(row.repairHours)} ч ремонт</small></td><td>{percent(row.availability * row.performance * row.quality / 10000)}<small>A {row.availability}% · P {row.performance}% · Q {row.quality}%</small></td><td>{row.vibration === null ? 'Не измеряется' : <><strong>{number(row.vibration)}</strong><small>Индекс · порог {row.threshold}</small></>}</td><td><Badge tone={row.maintenance ? 'amber' : 'green'}>{row.maintenance ? 'Внеплановый осмотр' : 'В работе'}</Badge></td></tr>)}</tbody></table></div><p className="ph-caption">КТГ = (плановый фонд − аварийный ремонт) / фонд. MTBF = часы работоспособности / число отказов. OEE = готовность × производительность × качество; значения A/P/Q — синтетические месячные измерения.</p></Panel>
    <Note tone="amber" icon="alert"><strong>EQ-CNC-01: требуется внеплановый осмотр шпинделя.</strong> Индекс вибронагрузки 7,1 превышает порог 5. Индекс безразмерный; порог является учебной настройкой. <button className="cell-link" onClick={() => navigate('executive', 'actions')}>Открыть наряд ОГМ →</button></Note>
    <Panel title="Баланс потерь времени" eyebrow="ПРОСТОИ · ФАКТИЧЕСКИЕ ЧАСЫ"><div className="ph-loss-chart">{timeLosses.map(row => <div key={row.label}><span>{row.label}</span><div className="ph-loss-track"><span style={{ width: `${row.hours / lossTotal * 100}%`, background: row.color }}/></div><strong>{number(row.hours)} ч</strong><small>{percent(row.hours / lossTotal * 100)}</small></div>)}</div><p className="ph-caption">Итого {number(lossTotal)} ч непересекающихся интервалов журнала MES. Аварийный ремонт 48 ч = 38,4 + 6,4 + 3,2 ч по парку. Доработки 46,5 нормо-часов в эту диаграмму не включены.</p></Panel>
    <Panel title="Длительность сопоставимых операций" eyebrow="ПЛАН / ФАКТ · АКТИВНАЯ ОБРАБОТКА"><div className="table-wrap"><table><thead><tr><th>Операция / группа сравнения</th><th>Норма, мин</th><th>Медиана, мин</th><th>Отклонение</th><th>Завершено / повторов</th></tr></thead><tbody>{operationDurations.map(row => <tr key={row.operation}><td><strong>{row.operation}</strong><small>{row.group}</small></td><td>{number(row.normMinutes)}</td><td>{number(row.medianMinutes)}</td><td className={row.medianMinutes / row.normMinutes > 1.05 ? 'text-amber' : 'text-sub'}>+{percent((row.medianMinutes / row.normMinutes - 1) * 100)}</td><td>{row.finishedRuns} / {row.repeatedRuns}</td></tr>)}</tbody></table></div><p className="ph-caption">Медиана — активное время завершённых первичных запусков по журналу MES, без ожиданий и повторов. Сравниваются одинаковые изделия, программы и ревизии. Повторы посчитаны отдельно: {managerSnapshot.reworked}; незавершённые запуски не входят в медиану.</p></Panel>
  </>;
}

function ActionsView({ route, openItem }: ViewProps) {
  const [initial] = useState(() => { try { return { rows: readExecutiveApprovals(), error: '' }; } catch (error) { return { rows: [], error: error instanceof Error ? error.message : 'Не удалось прочитать журнал виз.' }; } });
  const [approvals, setApprovals] = useState<ExecutiveApproval[]>(initial.rows);
  const [error, setError] = useState(initial.error);
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState<string | null>(null);
  const [verified, setVerified] = useState<Record<string, boolean>>({});
  const pending = pendingExecutiveActions(verified);
  useEffect(() => { void (async () => { try { setApprovals(await loadExecutiveApprovals()); } catch (error) { setError(error instanceof Error ? error.message : 'Журнал недоступен'); } })(); }, []);
  useEffect(() => { let active = true; void Promise.all(approvals.map(async row => [row.actionId, await verifyExecutiveApproval(row)] as const)).then(rows => { if (active) setVerified(Object.fromEntries(rows)); }); return () => { active = false; }; }, [approvals]);
  const approve = async (id: string) => { setBusy(id); try { const next = await signExecutiveAction(id, route.role); setApprovals(next); setVerified(current => ({ ...current, [id]: true })); setError(''); setNotice('Согласовано Директором производства · Подписано ЭЦП. Проверка подписи пройдена; сообщение сохранено в очереди доставки.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось подписать и сохранить решение.'); } finally { setBusy(null); } };
  return <>
    <div className="ph-decision-intro"><div><span className="eyebrow">ВИЗА РУКОВОДИТЕЛЯ</span><h2>Решения, которые меняют ход производства</h2><p>Рекламация, техническое обслуживание и маршрут доработки — с основаниями и ответственным получателем.</p></div><Badge tone={pending ? 'amber' : 'green'}>{pending ? `${pending} ожидают визы` : <><Icon name="check" size={14}/>Все решения подписаны</>}</Badge></div>
    <Note>Виза подписывается проверяемой демонстрационной ЭЦП ECDSA P-256 / SHA-256 без доверенного сертификата. Подпись, автор, время и очередь сохраняются сервером. Внешняя доставка 1С/ОГМ/MES остаётся демонстрационной; согласование маршрута не заменяет выпуск ОТК.</Note>
    {error && <div role="alert"><Note tone="red">{error}</Note></div>}{notice && <div role="status"><Note tone="green" icon="check">{notice}</Note></div>}
    <div className="ph-actions">{executiveActions.map((action, index) => { const approval = approvals.find(row => row.actionId === action.id); return <Panel key={action.id} title={action.title} eyebrow={`РЕШЕНИЕ 0${index + 1} · ${action.target}`}>
      <div className="ph-action-body"><div><div className="ph-inline-actions"><button className="cell-link mono" onClick={() => openItem(action.item)}>{action.item} · паспорт <Icon name="arrow" size={14}/></button>{action.equipment && <span className="mono text-sub">{action.equipment}</span>}</div><p>{action.basis}</p><p className="ph-caption">Результат: {action.effect}</p></div><div className="ph-action-control">{approval && <><Badge tone={verified[action.id] ? 'green' : approval.signature && verified[action.id] === false ? 'red' : 'amber'}>{verified[action.id] ? 'Согласовано Директором производства · Подписано ЭЦП' : approval.signature ? verified[action.id] === false ? 'Подпись не прошла проверку' : 'Проверка ЭЦП…' : 'Согласовано ранее · без ЭЦП'}</Badge><small>DIRECTOR-DEMO · {new Date(approval.approvedAt).toLocaleString('ru-RU')}</small>{verified[action.id] && <small>Подписано: {new Date(approval.signature!.signedAt).toLocaleString('ru-RU')}</small>}<span className="ph-caption">Локальная очередь → {approval.target}</span></>}{!approval?.signature && <Button primary icon="check" disabled={!!initial.error || !!busy} onClick={() => { void approve(action.id); }}>{busy === action.id ? 'Подпись и проверка…' : approval ? 'Подписать согласование ЭЦП' : action.button}</Button>}</div></div>
    </Panel>; })}</div>
    <Panel title="Журнал виз и передачи" eyebrow="ЛОКАЛЬНЫЙ АУДИТ · СНИМОК EXEC-2026-02-v1"><div className="table-wrap"><table><thead><tr><th>Решение / сообщение</th><th>Автор</th><th>Время визы</th><th>Получатель</th><th>Доставка</th></tr></thead><tbody>{approvals.map(row => <tr key={row.actionId}><td><strong>{executiveActions.find(action => action.id === row.actionId)?.title}</strong><small className="mono">{row.messageId}</small></td><td>{row.actor}</td><td>{new Date(row.approvedAt).toLocaleString('ru-RU')}</td><td>{row.target}</td><td><Badge tone="amber">В локальной очереди</Badge></td></tr>)}{!approvals.length && <tr><td colSpan={5}>Визы ещё не выданы. Записи появятся после согласования решения.</td></tr>}</tbody></table></div><p className="ph-caption">Повторное нажатие не создаёт вторую визу или сообщение. Исходные события и решения ОТК сохраняются отдельно. Локальный журнал демонстрирует авторство и основания; серверная авторизация и неизменяемый аудит относятся к промышленному контуру.</p></Panel>
  </>;
}

export function ProductionHeadView(props: ViewProps) {
  const section = props.route.section || 'balance';
  const context = section === 'balance' ? 'Баланс восстановления · 5 проблемных деталей' : section === 'personnel' ? 'Аудит смен и работы персонала' : section === 'reports' ? 'Печатные документы · фильтры периода и заказа' : `Цех космического приборостроения · ${managerSnapshot.checked} проверенных изделий`;
  return <div className="production-head"><div className="ph-snapshot"><span><Icon name="database" size={16}/>{managerSnapshot.period}</span><span>{context}</span><Badge tone="blue">Учебные данные</Badge></div><p className="ph-caption">Сценарные показатели кабинета отделены от демопотока. Ссылки на паспорта открывают исходную историю изделий; аудит персонала использует условные ФИО.</p>{section === 'personnel' ? <PersonnelView/> : section === 'reports' ? <ExecutiveReportGenerator/> : section === 'actions' ? <ActionsView {...props}/> : section === 'analytics' ? <><CommandCenter {...props}/><div id="enterprise-pareto" className="ph-enterprise-stack"><ParetoView {...props}/></div><details className="ph-equipment-details"><summary><Icon name="cpu"/>Надёжность критичного оборудования и потери времени</summary><div className="ph-enterprise-stack"><EquipmentView {...props}/></div></details></> : <RepairBalanceView {...props}/>}</div>;
}
