import { useEffect, useMemo, useState } from 'react';
import { cases, defectNames, events, mediaIndex, operations, type Scope } from './domain';
import { Badge, Button, Empty, Icon, Metric, Note, Panel } from './ui';
import { Modal } from './dialogs';
import { regionLabel } from './controller-case';
import type { ViewProps } from './views';
import { buildTechnologistAnalytics, dayKey, type AnalyticsFilter, type TechnologistAnalytics } from './technologist-analytics';
import { generateTechnologistReport, trendChartSvg, type ReportOptions } from './technologist-report';

const numeric=(value:number|undefined)=>value==null?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(value);
const darkSvg=(value:string)=>value.replaceAll('#253e50','#c5dbe8').replaceAll('#526878','#99b5c8').replaceAll('#dbe3e8','#334b5d');
function initialFilters(scope:Scope):AnalyticsFilter {
  const dates=events.filter(event=>['inspection_result','operation_started'].includes(event.event_type)).map(event=>dayKey(event.occurred_at)).sort();
  const fallback={from:dates[0]??'',to:dates.at(-1)??'',line:'all',equipment:'all',defect:'all',scope};
  try { const stored=JSON.parse(sessionStorage.getItem('orbita-tech-analytics-filter')??'null'); if(stored && typeof stored==='object') return {...fallback,...Object.fromEntries(Object.entries(stored).filter(([key,value])=>['from','to','line','equipment','defect'].includes(key) && typeof value==='string'))}; } catch { /* Use the accepted dataset range. */ }
  return fallback;
}
function CasesTable({model,openCase}:{model:TechnologistAnalytics;openCase:ViewProps['openCase']}) {
  return model.confirmed.length?<div className="table-wrap"><table><thead><tr><th>Изделие / дефект</th><th>Разбор причины</th><th>Следующий шаг</th><th>Основание</th></tr></thead><tbody>{model.confirmed.map(record=>{
    const state=model.caseStates[record.id];const pending=model.pending.filter(row=>row.record.id===record.id);
    return <tr key={record.id}><td><button className="cell-link" onClick={()=>openCase(record.item,record.id)}>{record.item} · {defectNames[record.type]}</button><small>{regionLabel(record.region)}</small></td><td><Badge tone={state==='confirmed'?'green':state==='revision'?'amber':state==='hypothesis'?'blue':'muted'}>{model.states.find(row=>row.id===state)?.label}</Badge></td><td>{pending.length?`Ожидаем ${pending.length} ответов`:state==='revision'?'Пересмотреть новые факты':state==='needed'||state==='hypothesis'?'Проверить основания и альтернативы':state==='unknown'?'Уточнить недостающие сведения':'Актуальный вывод сохранён'}</td><td className="mono">{record.review?.event_id ?? record.decisions.find(event=>event.data.decision==='confirmed')?.event_id}</td></tr>;
  })}</tbody></table></div>:<Empty title="Подтверждённых дел в этом срезе нет" text="Измените период, станок или тип дефекта."/>;
}
function StateChart({model}:{model:TechnologistAnalytics}) {
  const colors=['#cfad75','#69add6','#8bc5ab','#879daa','#da9092'];const total=model.confirmed.length;
  let accumulated=0;
  const stops=model.states.filter(row=>row.count).map(row=>{const i=model.states.indexOf(row);const begin=accumulated;accumulated+=row.count/Math.max(total,1)*100;return `${colors[i]} ${begin}% ${accumulated}%`;});
  return <div className="ta-state-chart"><div className="ta-ring" role="img" aria-label={`${total} дел: ${model.states.map(row=>`${row.label} ${row.count}`).join(', ')}`} style={{background:stops.length?`conic-gradient(${stops.join(',')})`:'#304654'}}><span><b>{total}</b><small>дел</small></span></div><div className="ta-legend">{model.states.map((row,index)=><div key={row.id}><i style={{background:colors[index]}}/><span>{row.label}</span><strong>{row.count}</strong></div>)}</div></div>;
}
function Coverage({model}:{model:TechnologistAnalytics}) {
  return <div className="ta-coverage">{model.coverage.map(row=><div key={row.label}><div><span>{row.label}</span><strong>{row.count} / {row.total}</strong></div><div className="ta-progress"><i style={{width:`${row.rate??0}%`}}/></div><small>{row.rate==null?'Не применяется в этом срезе':`${numeric(row.rate)}% дел с этим источником`}</small></div>)}</div>;
}
const defaults:ReportOptions={title:'Качество и обстоятельства производства',author:'',defects:true,equipment:true,operations:true,cases:true};
function ReportBuilder({model}:{model:TechnologistAnalytics}) {
  const [options,setOptions]=useState(defaults);const [snapshot,setSnapshot]=useState<{html:string;at:string}|null>(null);const [preview,setPreview]=useState(false);
  const generate=()=>{const at=new Date().toISOString();setSnapshot({at,html:generateTechnologistReport(model,options,at,regionLabel)});setPreview(true);};
  const download=()=>{if(!snapshot)return;const url=URL.createObjectURL(new Blob([snapshot.html],{type:'text/html;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`orbita-technologist-${snapshot.at.slice(0,10)}.html`;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <><Panel title="Отчёт технолога" eyebrow="СНИМОК ВЫБРАННОГО СРЕЗА"><div className="ta-report-layout"><div className="ta-report-form"><label>Название отчёта<input aria-label="Название отчёта" value={options.title} onChange={event=>setOptions({...options,title:event.target.value})}/></label><label>Подготовил<input aria-label="Автор отчёта" value={options.author} onChange={event=>setOptions({...options,author:event.target.value})} placeholder="ФИО / подразделение"/></label><fieldset><legend>Состав отчёта</legend>{([['defects','Дефекты, динамика и полнота данных'],['equipment','Контроль и предупреждения по станкам'],['operations','Время сопоставимых операций'],['cases','Дела, запросы и ID оснований']] as const).map(([id,label])=><label key={id}><input type="checkbox" checked={options[id]} onChange={event=>setOptions({...options,[id]:event.target.checked})}/>{label}</label>)}</fieldset><Button primary onClick={generate} disabled={!options.title.trim() || ![options.defects,options.equipment,options.operations,options.cases].some(Boolean)}>Сформировать отчёт</Button>{snapshot&&<div className="ta-report-actions"><Button onClick={()=>setPreview(true)}>Просмотреть снимок</Button><Button onClick={download}>Скачать HTML</Button></div>}</div><div className="ta-report-explanation"><Icon name="analytics" size={30}/><h3>Факты, графики, следующие действия</h3><p>Отчёт использует фильтры над панелью. В него входят расчёты, графики, открытые вопросы и ссылки на исходные события.</p><dl><div><dt>Дефекты / изделия</dt><dd>{model.confirmed.length} / {model.defectiveItems}</dd></div><div><dt>Запуски в срезе</dt><dd>{model.runRows.length}</dd></div><div><dt>Ожидаются ответы</dt><dd>{model.pending.length}</dd></div></dl><p>Скачанный HTML содержит текст и графику, работает без интернета. Для PDF используйте кнопку печати внутри отчёта.</p><small>Сформированный снимок сохраняет значения на момент создания; для новых данных сформируйте отчёт повторно.</small></div></div></Panel>{preview&&snapshot&&<Modal title="Предпросмотр отчёта технолога" className="ta-report-dialog" onClose={()=>setPreview(false)}><div className="ta-report-preview-header"><div><span className="eyebrow">ОТЧЁТ ТЕХНОЛОГА</span><h2>Готовый отчёт</h2></div><Button onClick={download}>Скачать HTML</Button><button className="icon-button" aria-label="Закрыть отчёт" onClick={()=>setPreview(false)}><Icon name="close"/></button></div><iframe title="Сформированный отчёт технолога" srcDoc={snapshot.html}/></Modal>}</>;
}

export function TechnologistAnalyticsView({route,scope,openItem,openCase}:ViewProps) {
  const [filter,setFilter]=useState(()=>initialFilters(scope));
  useEffect(()=>{try{sessionStorage.setItem('orbita-tech-analytics-filter',JSON.stringify(filter));}catch{/* Optional filter persistence. */}},[filter]);
  const model=useMemo(()=>buildTechnologistAnalytics({events,cases,operations,mediaIds:mediaIndex.map(asset=>asset.asset_id),defectNames},{...filter,scope}),[filter,scope,events,cases,operations]);
  const invalid=!!filter.from&&!!filter.to&&filter.from>filter.to;
  const change=(key:keyof AnalyticsFilter,value:string)=>setFilter(current=>({...current,[key]:value}));
  const reset=()=>{sessionStorage.removeItem('orbita-tech-analytics-filter');setFilter(initialFilters(scope));};
  const equipmentIds=[...new Set(events.filter(event=>event.event_type==='operation_started'&&event.equipment_id).map(event=>event.equipment_id!))].sort();
  return <div className="ta-dashboard"><div className="ta-filter-bar"><label>С<input type="date" aria-label="Период с" value={filter.from} onChange={event=>change('from',event.target.value)}/></label><label>По<input type="date" aria-label="Период по" value={filter.to} onChange={event=>change('to',event.target.value)}/></label><label>Линия<select aria-label="Линия аналитики" value={filter.line} onChange={event=>change('line',event.target.value)}><option value="all">Все линии</option>{[...new Set(events.map(event=>event.line_id))].sort().map(id=><option key={id}>{id}</option>)}</select></label><label>Оборудование<select aria-label="Станок аналитики" value={filter.equipment} onChange={event=>change('equipment',event.target.value)}><option value="all">Все станки</option>{equipmentIds.map(id=><option key={id}>{id}</option>)}</select></label><label>Дефект<select aria-label="Дефект аналитики" value={filter.defect} onChange={event=>change('defect',event.target.value)}><option value="all">Все типы</option>{Object.entries(defectNames).filter(([id])=>id!=='UNASSESSABLE').map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><Button onClick={reset}>Сбросить фильтры</Button></div><p className="ta-filter-note">Дефекты отбираются по дате первого наблюдения, запуски — по дате начала. Часовой пояс: Москва. Источники и версии профилей доступны в карточках операций.</p>
    {invalid?<Note tone="amber">Дата начала периода должна быть не позже даты окончания.</Note>:<>
      <div className="metric-grid"><Metric label="Подтверждённые дефекты" value={model.confirmed.length} note={`${model.defectiveItems} изделий · ${model.incoming} входных дефектов`} icon="quality"/><Metric label="Причина установлена" value={model.established} note="Только актуальные выводы технолога" icon="investigation" tone="green"/><Metric label="Запуски с предупреждением" value={model.warnings} note={`Из ${model.runRows.length} принятых запусков`} icon="production" tone="amber"/><Metric label="Ожидаются ответы" value={model.pending.length} note="Запросы мастеру и ОТК в этом срезе" icon="clock"/></div>
      {route.section==='reports'?<ReportBuilder model={model}/>:<>
        {route.section==='causes'&&<><div className="ta-chart-grid"><Panel title="Ход расследований" eyebrow="ДЕФЕКТ И ПРИЧИНА — ОТДЕЛЬНЫЕ СТАТУСЫ"><StateChart model={model}/></Panel><Panel title="Что требует внимания" eyebrow="ПО ПРИНЯТЫМ ФАКТАМ"><ol className="ta-insights">{model.insights.slice(0,4).map(text=><li key={text}>{text}</li>)}</ol></Panel></div><div className="ta-chart-grid"><Panel title="Динамика контроля" eyebrow="ПО ДНЯМ НАБЛЮДЕНИЯ"><div className="ta-svg-chart" dangerouslySetInnerHTML={{__html:darkSvg(trendChartSvg(model.daily))}}/><div className="ta-inline-legend"><span><i style={{background:'#307c9b'}}/>Изделия с признаками</span><span><i style={{background:'#b36632'}}/>Подтверждённые дефекты</span></div><p className="chart-caption">Подтверждения учитываются по текущему решению ОТК. У одного изделия может быть несколько дефектов.</p></Panel><Panel title="Полнота оснований" eyebrow="ДЛЯ ПОДТВЕРЖДЁННЫХ ДЕЛ"><Coverage model={model}/><p className="chart-caption">Для журнала станка знаменатель включает только дела со связанным запуском; входные случаи исключены.</p></Panel></div></>}
        {route.section==='quality'&&<div className="ta-chart-grid"><Panel title="Какие дефекты повторяются" eyebrow="ПОДТВЕРЖДЕНИЯ ОТК"><div className="ta-defect-bars">{model.byDefect.map(row=><button key={row.id} onClick={()=>change('defect',row.id)}><span>{row.label}</span><strong>{row.count}</strong><i style={{width:`${row.count/Math.max(model.confirmed.length,1)*100}%`}}/></button>)}{!model.byDefect.length&&<Empty title="Нет подтверждённых дефектов" text="Измените выбранный срез."/>}</div><p className="chart-caption">Нажмите тип, чтобы отфильтровать дела и остальные показатели.</p></Panel><Panel title="Чем можно обосновать вывод" eyebrow="ПОКРЫТИЕ ИСТОЧНИКАМИ"><Coverage model={model}/><Note>Отсутствующий кадр не заменяется изображением другого изделия. Для внешнего признака доступны осмотр ОТК и сведения мастера.</Note></Panel></div>}
        {route.section==='equipment'&&<Panel title="Контроль после операций на оборудовании" eyebrow="ЯВНЫЙ ЗНАМЕНАТЕЛЬ"><div className="table-wrap"><table><thead><tr><th>Станок</th><th>Запуски</th><th>Контроль оценён</th><th>Признаки CV</th><th>Подтверждение ОТК</th><th>Предупреждения</th><th>Журнал станка</th></tr></thead><tbody>{model.equipment.map(row=><tr key={row.id}><td><button className="cell-link" onClick={()=>change('equipment',row.id)}>{row.id}</button></td><td>{row.runs}</td><td>{row.checked}</td><td>{row.signs}</td><td>{row.confirmedRuns} / {row.checked}<small>{row.rate==null?'Доля не рассчитана':`${numeric(row.rate)}%`}</small></td><td>{row.warnings} запусков</td><td>{row.telemetry} / {row.runs}</td></tr>)}</tbody></table></div><p className="chart-caption">Подтверждения — оценённые запуски с подтверждённым выбранным дефектом после операции. Это не рейтинг виновных станков. Незавершённые и неоценённые запуски не входят в знаменатель доли.</p></Panel>}
        {route.section==='time'&&<Panel title="Завершённость и доработки" eyebrow="ПО ПРИНЯТЫМ НАЧАЛАМ И ОКОНЧАНИЯМ"><div className="table-wrap"><table><thead><tr><th>Операция / станок</th><th>Участок / исполнитель</th><th>Программа / версия</th><th>Проход</th><th>Завершено / всего</th><th>Медиана</th><th>Диапазон</th><th>Сумма времени</th></tr></thead><tbody>{model.durationGroups.map(row=><tr key={row.id}><td><button className="cell-link" onClick={()=>openItem(row.items[0])}>{row.label}</button><small>{row.equipment} · {row.type}</small></td><td>{row.station}<small>{row.executor}</small></td><td>{row.programName} · {row.revision}<small>{row.shiftName}{!row.comparable?' · версия не подтверждена':''}</small></td><td>{row.rework?'Повторный':'Первичный'}</td><td>{row.finished} / {row.runs}</td><td>{numeric(row.median)} мин</td><td>{numeric(row.min)}–{numeric(row.max)} мин</td><td>{numeric(row.total)} мин</td></tr>)}</tbody></table></div><p className="chart-caption">Это время между началом и завершением, включая возможные паузы. Незавершённые работы учитываются в количестве, но не в медиане и сумме времени.</p></Panel>}
        <Panel title="Дела в выбранном срезе" eyebrow="ОТ ПОКАЗАТЕЛЯ К ИСХОДНЫМ СОБЫТИЯМ"><CasesTable model={model} openCase={openCase}/></Panel>
      </>}
    </>}
  </div>;
}
