import type { TechnologistAnalytics } from './technologist-analytics';
export const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]!));
const n = (value: number | undefined) => value == null ? 'Нет данных' : new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(value);
export interface ReportOptions { title: string; author: string; defects: boolean; equipment: boolean; operations: boolean; cases: boolean }
export function barChartSvg(rows: {label:string;count:number}[], suffix = '', color = '#307c9b') {
  if (!rows.length) return '<p class="empty">В выбранном срезе нет данных.</p>';
  const height = rows.length * 40 + 20; const max = Math.max(...rows.map(row=>row.count),1);
  return `<svg role="img" aria-label="Распределение показателей" viewBox="0 0 700 ${height}" xmlns="http://www.w3.org/2000/svg">${rows.map((row,index)=>{
    const y=index*40+10;
    return `<text x="0" y="${y+12}" fill="#253e50" font-size="12">${escapeHtml(row.label)}</text><rect x="245" y="${y}" width="${Math.max(0,row.count/max*385)}" height="20" rx="3" fill="${color}"/><text x="${Math.min(640,255+row.count/max*385)}" y="${y+14}" fill="#253e50" font-size="12">${n(row.count)}${escapeHtml(suffix)}</text>`;
  }).join('')}</svg>`;
}
export function trendChartSvg(rows: TechnologistAnalytics['daily']) {
  if (!rows.length) return '<p class="empty">Наблюдений в выбранном периоде нет.</p>';
  const max=Math.max(...rows.flatMap(row=>[row.signals,row.defects]),1); const x=(index:number)=>45+index*600/Math.max(rows.length-1,1); const y=(count:number)=>180-count/max*140;
  const series=[{key:'signals' as const,color:'#307c9b'},{key:'defects' as const,color:'#b36632'}];
  return `<svg role="img" aria-label="Признаки и подтверждённые дефекты по дням" viewBox="0 0 700 220" xmlns="http://www.w3.org/2000/svg">${[0,.5,1].map(f=>`<line x1="45" x2="650" y1="${y(max*f)}" y2="${y(max*f)}" stroke="#dbe3e8"/><text x="5" y="${y(max*f)+5}" fill="#526878" font-size="11">${n(max*f)}</text>`).join('')}${series.map(s=>`<polyline points="${rows.map((row,index)=>`${x(index)},${y(row[s.key])}`).join(' ')}" fill="none" stroke="${s.color}" stroke-width="3"/>${rows.map((row,index)=>`<circle cx="${x(index)}" cy="${y(row[s.key])}" r="4" fill="${s.color}"/>`).join('')}`).join('')}${rows.map((row,index)=>`<text x="${x(index)}" y="205" text-anchor="middle" fill="#526878" font-size="11">${row.label}</text>`).join('')}</svg>`;
}
function table(headers: string[], rows: unknown[][]) { return `<table><thead><tr>${headers.map(header=>`<th>${escapeHtml(header)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${escapeHtml(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }
/** A frozen, portable report built from the same snapshot as the dashboard. */
export function generateTechnologistReport(model: TechnologistAnalytics, options: ReportOptions, createdAt: string, regionName: (region:string)=>string = region=>region) {
  const period=`${model.filter.from || 'начало набора'} — ${model.filter.to || 'конец набора'}`;
  const slices=[period,model.filter.line==='all'?'Все линии':model.filter.line,model.filter.equipment==='all'?'Все станки':model.filter.equipment,model.filter.scope==='all'?'Все смены':model.filter.scope,model.filter.defect==='all'?'Все типы дефектов':model.filter.defect].join(' · ');
  const defectNames=new Map(model.byDefect.map(row=>[row.id,row.label]));
  const body=`<header><span class="eyebrow">ОРБИТА.QC · АНАЛИТИКА ТЕХНОЛОГА</span><h1>${escapeHtml(options.title || 'Разбор качества и обстоятельств производства')}</h1><p>${escapeHtml(slices)}</p><small>Сформирован: ${escapeHtml(new Date(createdAt).toLocaleString('ru-RU'))}${options.author.trim()?` · Автор: ${escapeHtml(options.author)}`:''}. Снимок принятых данных.</small></header>
  <div class="metrics"><div><b>${model.confirmed.length}</b>подтверждённых дефектов</div><div><b>${model.defectiveItems}</b>изделий с дефектами</div><div><b>${model.established}</b>актуальных установленных причин</div><div><b>${model.pending.length}</b>запросов без ответа</div></div>
  <section><h2>Что требует внимания</h2><ul>${model.insights.map(text=>`<li>${escapeHtml(text)}</li>`).join('')}</ul></section>
  ${options.defects?`<section><h2>Подтверждённые дефекты и ход разбора</h2><div class="charts"><div>${barChartSvg(model.byDefect)}</div><div>${barChartSvg(model.states.map(row=>({label:row.label,count:row.count})), '', '#68899c')}</div></div><h3>Динамика наблюдений</h3>${trendChartSvg(model.daily)}<p class="caption">Синий: изделия с признаками за день. Оранжевый: подтверждённые дефекты по дате первого наблюдения, с учётом текущего решения ОТК. Признак не является подтверждением дефекта.</p><h3>Полнота оснований</h3>${table(['Источник','Представлен / дела','Доля'],model.coverage.map(row=>[row.label,`${row.count} / ${row.total}`,row.rate==null?'Не применимо':`${n(row.rate)}%`]))}</section>`:''}
  ${options.equipment?`<section><h2>Оборудование: контекст, контроль и предупреждения</h2>${barChartSvg(model.equipment.filter(row=>row.rate!=null).map(row=>({label:row.id,count:row.rate!})), '%')}<p class="caption">Доля оценённых запусков с подтверждением ОТК; числитель и знаменатель приведены в таблице.</p>${table(['Станок','Запуски','Оценённый контроль','С подтверждением ОТК','Предупреждения'],model.equipment.map(row=>[row.id,row.runs,row.checked,`${row.confirmedRuns} / ${row.checked}${row.rate==null?'':` (${n(row.rate)}%)`}`,row.warnings]))}<p class="caption">Доля относится к оценённым запускам, после которых ОТК подтвердил выбранный дефект. Связь со станком не устанавливает его вину. Предупреждения считаются по запускам, а не по числу образцов.</p></section>`:''}
  ${options.operations?`<section><h2>Полное время запусков</h2>${barChartSvg(model.durationGroups.filter(row=>row.comparable && row.median!=null).slice(0,8).map(row=>({label:`${row.equipment} · ${row.shift} · ${row.rework?'повторный':'первичный'}`,count:row.median!})), ' мин')}<p class="caption">Медианы завершённых работ с известной версией программы. Полные условия групп — в таблице.</p>${table(['Операция / станок','Участок / исполнитель','Программа / версия / смена','Проход','Завершено / всего','Медиана, мин','Диапазон, мин'],model.durationGroups.map(row=>[`${row.label} · ${row.equipment}`,`${row.station} · ${row.executor}`,`${row.programName} · ${row.revision} · ${row.shiftName}`,row.rework?'Повторный':'Первичный',`${row.finished} / ${row.runs}`,n(row.median),row.min==null?'Нет данных':`${n(row.min)}–${n(row.max)}${row.comparable?'':' (версия не известна)'}`]))}<p class="caption">Группы разделены по типу изделия, операции, станку, программе, ревизии, смене и первичному/повторному проходу. Время между началом и завершением включает возможные ожидания и паузы; незавершённые запуски в медиану не входят.</p></section>`:''}
  ${options.cases?`<section><h2>Дела и основания для следующего действия</h2>${table(['Дело / изделие','Дефект / зона','Вывод','Следующее действие / основание'],model.confirmed.map(record=>{
    const state=model.states.find(row=>row.id===model.caseStates[record.id])?.label ?? 'Без заключения';
    const outstanding=model.pending.filter(row=>row.record.id===record.id).map(row=>row.request.data.reason).join('; ');
    return [`${record.id}\n${record.item}`,`${defectNames.get(record.type)??record.type} · ${regionName(record.region)}`,`${state}${record.review?`\n${record.review.data.reason}`:''}`,outstanding || String(record.review?.data.missing_data || 'Проверить обстоятельства и оформить актуальный вывод')];
  }))}<h3>Проверяемые ссылки на записи</h3>${table(['Дело','Сигнал','Подтверждение ОТК','Вывод / основания'],model.confirmed.map(record=>[record.id,record.observations[0].event_id,record.decisions.find(event=>event.data.decision==='confirmed')?.event_id??'Нет',`${record.review?.event_id??'Нет'}\n${record.review?.data.basis_event_ids?.join(', ')??''}`]))}</section>`:''}
  <footer>Цеховой контур №1 · Статистика принятых событий и заключений технолога. <details><summary>Происхождение данных</summary>Демонстрационный набор, включая синтетическую телеметрию и справочные пределы. Реальная интеграция предприятия и проверка нормативных документов не подключены.</details></footer>`;
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(options.title||'Отчёт технолога')}</title><style>
  *{box-sizing:border-box}body{margin:0;background:#e9eef1;color:#253e50;font:13px Arial,sans-serif;line-height:1.5}main{max-width:1040px;margin:24px auto;background:white;padding:36px}header{border-bottom:3px solid #307c9b;padding-bottom:20px}h1{font-size:26px;line-height:1.25;margin:8px 0}h2{font-size:18px;margin:0 0 14px}h3{font-size:14px;margin:20px 0 8px}.eyebrow{letter-spacing:.12em;font-size:10px;color:#526878}header p{margin:10px 0;font-size:12px}small,.caption,footer{font-size:11px;color:#526878}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.metrics div{padding:14px;background:#eff5f8;border:1px solid #d3e0e6;font-size:11px}.metrics b{display:block;font-size:28px;color:#245570}section{margin:28px 0}ul{padding-left:20px}li{margin:7px 0}.charts{display:grid;grid-template-columns:1fr 1fr;gap:24px}svg{width:100%;height:auto}table{width:100%;border-collapse:collapse;font-size:11px;margin:12px 0;table-layout:fixed}th{background:#e8f1f6;text-align:left}th,td{padding:9px 8px;border-bottom:1px solid #d3e0e6;vertical-align:top;overflow-wrap:anywhere;white-space:pre-line}footer{border-top:1px solid #bccfd9;padding-top:16px}.empty{color:#526878}button{font:inherit;padding:9px 14px;border:1px solid #a0bbc9;border-radius:4px;background:#245570;color:white;cursor:pointer}.print-control{max-width:1040px;margin:20px auto 0;display:flex;gap:12px;align-items:center}.print-control span{font-size:12px}@media(max-width:700px){main{padding:20px;margin:0}.metrics,.charts{grid-template-columns:1fr 1fr}.print-control{padding:12px}table{font-size:9px}}@page{size:A4;margin:14mm}@media print{body{background:white;font-size:10px}main{max-width:none;margin:0;padding:0}.print-control{display:none}h1{font-size:22px}h2{font-size:16px}.metrics{margin:18px 0}.metrics div{padding:10px}section{margin:20px 0}tr{break-inside:avoid}thead{display:table-header-group}h2,h3{break-after:avoid}svg{max-height:190px}th{background:#e8f1f6}*{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
  </style></head><body><div class="print-control"><button onclick="window.print()">Печать / сохранить PDF</button><span>В диалоге печати выберите «Сохранить как PDF».</span></div><main>${body}</main></body></html>`;
}
