import { useState } from 'react';
import { Badge, Note } from './ui';
import { time, type Case } from './domain';
import { investigationEvidence } from './technologist-evidence';
import { historicalBaseline as baseline, historicalDefectLabels, historicalRuns, parameterDelta, type HistoricalRun } from './mockData';

const sampleTime = (at: string) => new Date(at).toLocaleTimeString('ru-RU', {hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Europe/Moscow'});
const duration = (seconds: number) => `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')} мин`;
function RunCard({ run, current = false }: { run: HistoricalRun; current?: boolean }) {
  return <section className="tech-run-card"><header><span className="eyebrow">{current ? 'ИССЛЕДУЕМЫЙ ЗАПУСК' : 'ИСТОРИЧЕСКИЙ АРХИВ'}</span><h3>{current ? `${run.id}-MILLING-1` : run.id}</h3><Badge tone={run.status === 'SUCCESS' ? 'green' : 'amber'}>{run.status === 'SUCCESS' ? 'Эталон техпроцесса' : `Брак: ${historicalDefectLabels[run.defType ?? ''] ?? 'Дефект'}`}</Badge></header><dl className="tech-detail-list">{[['Время / оператор', `${time(run.occurredAt)} · ${run.operator}`], ['Станок / программа', `${run.equipment} · ${run.program} / ${run.revision}`], ['Шпиндель', `${run.spindleRpm} об/мин`], ['Подача', `${run.feedRate} мм/мин`], ['СОЖ', `${run.coolantBar.toFixed(1)} бар`], ['Индекс вибронагрузки', `${run.vibration.toFixed(1)}${run.vibration > baseline.warningThreshold ? ' · ВСПЛЕСК' : ''}`], ['Длительность', duration(run.durationSec)], ['Дефектов', run.defCount]].map(([name, value]) => <div key={name}><dt>{name}</dt><dd className={name === 'Индекс вибронагрузки' && run.vibration > baseline.warningThreshold ? 'text-amber' : ''}>{value}</dd></div>)}</dl><p>{run.comment}</p></section>;
}
export function HistoricalComparison({ record }: { record: Case }) {
  const [filter, setFilter] = useState('all');
  const [selected, setSelected] = useState('RUN-005');
  const rows = historicalRuns.filter(run => filter === 'all' || (filter === 'good' ? run.status === 'SUCCESS' : run.status === 'DEFECT'));
  const reference = rows.find(run => run.id === selected) ?? rows[0];
  const facts = investigationEvidence(record);
  const sample = facts.machine.find(event => event.data.parameter === 'vibration_index' && typeof event.data.value === 'number');
  const params = facts.machine.filter(event => typeof event.data.spindle_speed_rpm === 'number');
  const actual = params.reduce((peak, event) => Number(event.data.vibration_index) > Number(peak?.data.vibration_index ?? 0) ? event : peak, params[0]);
  const current: HistoricalRun = { ...historicalRuns.find(run => run.id === 'RUN-007')!,
    vibration: Math.max(Number(sample?.data.value ?? 0), ...params.map(event => Number(event.data.vibration_index ?? 0))),
    spindleRpm: Number(actual?.data.spindle_speed_rpm ?? 6050), feedRate: Number(actual?.data.feed_rate_mm_min ?? 485), coolantBar: Number(actual?.data.coolant_pressure_bar ?? 4.1),
    durationSec: facts.start && facts.finish ? (Date.parse(facts.finish.occurred_at) - Date.parse(facts.start.occurred_at)) / 1000 : 900,
    defType: record.type, defCount: facts.signal.data.defects?.length ?? 1,
    comment: record.type === 'BURR' ? 'Заусенец кромки B; протокол диагностики привода доступен в основаниях' : 'Царапина; вывод о механизме заусенца на этот случай не переносится',
    occurredAt: facts.start?.occurred_at ?? '', operator: facts.start?.actor_id ?? 'Не передан',
  };
  const diagnostic = facts.masterReports.find(event => event.data.diagnostic_confirmed === true);
  const delta = (a: number, b: number) => `${(parameterDelta(a, b) ?? 0) >= 0 ? '+' : ''}${parameterDelta(a, b)?.toFixed(1)}%`;
  return <section className="tech-info-card"><div className="tech-card-heading"><span className="eyebrow">СОПОСТАВЛЕНИЕ · АРХИВ ОПЕРАЦИЙ</span><h3>История фрезерования кронштейна</h3><p>20 запусков на EQ-CNC-01 · PRG-BRACKET-A, ревизия 3 · 16 годных и 4 с дефектами. Архив отделён от текущих производственных показателей.</p></div><div className="tech-compare-controls"><label>Выбор запуска<select aria-label="Сопоставимый запуск" value={reference.id} onChange={e => setSelected(e.target.value)}>{rows.map(run => <option key={run.id} value={run.id}>{run.id} ({time(run.occurredAt)}) — {run.id === 'RUN-005' ? 'Золотой эталон (Годно)' : run.status === 'SUCCESS' ? 'Годно' : historicalDefectLabels[run.defType ?? '']}</option>)}</select></label><label>Фильтр архива<select aria-label="Фильтр архива" value={filter} onChange={e => { setFilter(e.target.value); }}>{[['all', 'Все запуски'], ['good', 'Только эталоны (Годно)'], ['defect', 'С дефектами']].map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label></div><div className="tech-run-grid"><RunCard run={reference}/><RunCard run={current} current/></div><div className="tech-delta-grid"><article><small>Подача</small><strong>{delta(current.feedRate, reference.feedRate)}</strong><Badge tone={current.feedRate >= baseline.feedLower && current.feedRate <= baseline.feedUpper ? 'green' : 'amber'}>{current.feedRate >= baseline.feedLower && current.feedRate <= baseline.feedUpper ? 'В контрольном интервале' : 'Вне контрольного интервала'}</Badge></article><article><small>Вибрация</small><strong>{delta(current.vibration, reference.vibration)}</strong><Badge tone="amber">16:12 · {current.vibration} &gt; {baseline.warningThreshold}</Badge></article><article><small>Длительность</small><strong>{current.durationSec - reference.durationSec >= 0 ? '+' : '−'}{duration(Math.abs(current.durationSec - reference.durationSec))}</strong><span>Полное время операции</span></article></div><Note>В {baseline.sampleSize} успешных прогонах индекс &gt; 7.0 не фиксировался; среднее — {baseline.vibrationAvg}. Исторический коридор: {baseline.vibrationMin}–{baseline.vibrationMax}. Пик текущего запуска — {current.vibration}. Сравнение выявляет аномалию; механизм дефекта подтверждается отдельной диагностикой, доступной в основаниях.</Note>{diagnostic && <div className="tech-run-card"><Badge tone="green">Диагностический протокол · {String(diagnostic.data.diagnostic_id)}</Badge><h3>Связь с неисправностью привода проверена</h3><p>{diagnostic.data.comment}</p><small className="tech-source-line">{diagnostic.event_id} · {diagnostic.actor_id} · {time(diagnostic.occurred_at)} · Цеховой контур №1. Итоговый вывод записывает технолог.</small></div>}</section>;
}

export function VibrationTimeline({ record }: { record: Case }) {
  const facts = investigationEvidence(record);
  const detailed = facts.machine.filter(event => event.data.sample_window_seconds === 1);
  const samples = (detailed.length > 1 ? detailed : facts.machine).map(event => ({ event, value: event.data.parameter === 'vibration_index' ? Number(event.data.value) : typeof event.data.vibration_index === 'number' ? event.data.vibration_index : undefined })).filter((row): row is { event: typeof facts.machine[number]; value: number } => row.value != null && Number.isFinite(row.value)).sort((a,b) => Date.parse(a.event.occurred_at) - Date.parse(b.event.occurred_at));
  const [active, setActive] = useState<string>();
  if (!facts.start || !facts.finish || !samples.length || facts.runId !== 'RUN-007-MILLING-1') return null;
  const from = Date.parse(facts.start.occurred_at), to = Date.parse(facts.finish.occurred_at);
  const x = (at: string) => 55 + (Date.parse(at) - from) / (to - from) * 710;
  const max = Math.max(8, ...samples.map(row => row.value)), y = (v: number) => 220 - v / max * 180;
  const chosen = samples.find(row => row.event.event_id === active) ?? samples.reduce((a,b) => a.value > b.value ? a : b);
  return <figure className="tech-vibration"><figcaption><strong>Вибрация в ходе операции</strong><span>Исторический коридор: 2.0–3.5 · 16 успешных запусков. Красная линия — предельный порог предупреждения 5.0.</span></figcaption><svg viewBox="0 0 800 265" role="img" aria-label="График вибрации: исторический коридор 2.0–3.5, порог 5.0"><rect x="55" y={y(baseline.vibrationMax)} width="710" height={y(baseline.vibrationMin)-y(baseline.vibrationMax)} fill="#64b494" opacity=".18"/>{[0,2,3.5,5,7.1].map(v => <g key={v}><line x1="55" x2="765" y1={y(v)} y2={y(v)} stroke={v === 5 ? '#e7847b' : '#334653'} strokeDasharray={v === 5 ? '6 5' : '2 6'}/><text x="12" y={y(v)+4} fill="#a6becb" fontSize="12">{v}</text></g>)}<polyline fill="none" stroke="#a9cfe0" strokeWidth="2.5" points={samples.map(row => `${x(row.event.occurred_at)},${y(row.value)}`).join(' ')}/>{samples.map(row => <circle key={row.event.event_id} cx={x(row.event.occurred_at)} cy={y(row.value)} r={row.value > 5 ? 7 : 4} fill={row.value > 5 ? '#efad63' : '#9cc4d9'} tabIndex={0} role="button" aria-label={`${time(row.event.occurred_at)} ${row.event.event_id}: ${row.value}`} onMouseEnter={() => setActive(row.event.event_id)} onFocus={() => setActive(row.event.event_id)} onClick={() => setActive(row.event.event_id)} onKeyDown={e => { if(e.key==='Enter' || e.key===' ') {e.preventDefault();setActive(row.event.event_id);} }}><title>{sampleTime(row.event.occurred_at)} · {String(row.event.data.alarm_code ?? row.event.event_id)} — Индекс вибронагрузки: {row.value}</title></circle>)}{[0,.25,.5,.75,1].map(t => <text key={t} x={55+t*710} y="250" textAnchor="middle" fill="#a6becb" fontSize="12">{new Date(from+(to-from)*t).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'})}</text>)}</svg><div className="tech-chart-tooltip" role="status">{sampleTime(chosen.event.occurred_at)} · {String(chosen.event.data.alarm_code ?? chosen.event.event_id)} — Индекс вибронагрузки: <b>{chosen.value}</b><small>{chosen.event.event_id} · {chosen.event.source_id}</small></div></figure>;
}
